snippets/cbl: Add function to test tc-build on different distros
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/snippets/cbl b/snippets/cbl
--- a/snippets/cbl
+++ b/snippets/cbl
@@ -853,3 +853,80 @@ function cbl_path() {
         "-u"|"--unset") export PATH=${PATH/${CBL_BIN//\//\\/}:/} ;;
     esac
 }
+
+
+# Function to test build-{binutils,llvm}.sh in multiple Docker images
+function bld_llvm_bntls_sh() {(
+    CCACHE_FOLDER=${CBL}/git/ccache
+    LOG=$(mktemp); echo "Log: ${LOG}"
+    SCRIPT=$(mktemp --suffix=.sh)
+    TC_BLD=${CBL}/git/tc-build
+
+    mkdir -p "${CCACHE_FOLDER}"
+
+    # SC2016: Expressions don't expand in single quotes, use double quotes for that.
+    # shellcheck disable=SC2016
+    echo '#!/usr/env/bash
+
+PACKAGES=( ccache clang cmake git python )
+
+# Debian/Ubuntu
+if command -v apt-get &>/dev/null; then
+    PACKAGES+=( ca-certificates curl file gcc g++ make ninja-build texinfo zlib1g-dev )
+    case "$(cat /etc/os-release)" in
+        *buster*|*bionic*|*cosmic*|*disco*) PACKAGES+=( lld ) ;;
+    esac
+    apt-get update
+    apt-get upgrade -y
+    apt-get install --no-install-recommends -y "${PACKAGES[@]}"
+# Fedora
+elif command -v dnf &>/dev/null; then
+    PACKAGES+=( gcc gcc-c++ lld ninja-build zlib-devel )
+    dnf update -y
+    dnf install -y "${PACKAGES[@]}"
+# Arch
+elif command -v pacman &>/dev/null; then
+    PACKAGES+=( base-devel lld ninja )
+    pacman -Syyu --noconfirm
+    pacman -S --noconfirm "${PACKAGES[@]}"
+fi
+
+ccache -M 30G
+ccache --set-config=compression=true
+ccache --set-config=compression_level=9
+ccache --set-config=cache_dir=/ccache
+
+git clone /'"${TC_BLD##*/}"' /'"${TC_BLD##*/}"'2 && cd /'"${TC_BLD##*/}"'2
+
+./build-binutils.sh -t all || exit 1
+./build-llvm.sh CC=gcc || exit 1
+./build-llvm.sh CC=clang || exit 1
+
+for FILE in clang ld.lld aarch64-linux-gnu-ld arm-linux-gnueabi-ld powerpc64le-linux-gnu-ld powerpc-linux-gnu-ld ld; do
+    ./usr/bin/${FILE} --version || exit 1
+done' > "${SCRIPT}"
+
+    for IMAGE in ubuntu:xenial \
+                 ubuntu:bionic \
+                 ubuntu:cosmic \
+                 ubuntu:disco \
+                 archlinux/base:latest \
+                 fedora:latest \
+                 debian:stretch \
+                 debian:buster; do
+        docker run --interactive \
+                   --mount type=bind,source="${TC_BLD}",target=/"${TC_BLD##*/}",readonly \
+                   --mount type=bind,source="${CCACHE_FOLDER}",target=/ccache \
+                   --mount type=bind,source="${SCRIPT}",target=/script.sh \
+                   --rm \
+                   --tty \
+                   --workdir /"${TC_BLD##*/}" \
+                   "${IMAGE}" bash /script.sh || { echo "${IMAGE} failed" >> "${LOG}"; continue; }
+        echo "${IMAGE} successful" >> "${LOG}"
+    done
+
+    echo
+    echo "Results:"
+    cat "${LOG}"
+    echo
+)}
