snippets/cbl: Test kernel/common with tip of tree Clang
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/snippets/cbl b/snippets/cbl
--- a/snippets/cbl
+++ b/snippets/cbl
@@ -286,7 +286,7 @@ function bootk() {
         *) display_error "Invalid ARCH specified!"; return 1 ;;
     esac
 
-    KERNEL=${KERNEL_BUILD_FOLDER}/arch/${ARCH}/boot/${IMAGE}
+    KERNEL=${KERNEL_LOCATION:-${KERNEL_BUILD_FOLDER}}/arch/${ARCH}/boot/${IMAGE}
     [[ ! -f ${KERNEL} ]] && { display_error "Kernel doesn't exist! Please build one."; return 1; }
 
     # Update the images
@@ -627,4 +627,149 @@ function bldusr() {(
 
     # Build binutils
     bldbn -i
+)}
+
+
+# kernel/common build wrapper
+function kcbw() {(
+    OUT_FOLDER=${BUILD_FOLDER}/common
+    # SC2030: Modification of BUILD_FOLDER is local (to subshell caused by (..) group).
+    # shellcheck disable=SC2030
+    BUILD_FOLDER=${KERNEL_FOLDER}/build
+    COMMON_FOLDER=${KERNEL_FOLDER}/common
+    BRANCH=android-${1:-4.9}; shift
+
+    cd "${BUILD_FOLDER}" || die "wtf"
+
+    # SC1004: This backslash+linefeed is literal. Break outside single quotes if you just want to break the line.
+    # SC2016: Expressions don't expand in single quotes, use double quotes for that.
+    # shellcheck disable=SC1004,SC2016
+    echo 'ARCH=arm64
+BRANCH='"${BRANCH}"'
+CLANG_TRIPLE=aarch64-linux-gnu-
+CROSS_COMPILE=aarch64-linux-gnu-
+DEFCONFIG=cuttlefish_defconfig
+EXTRA_CMDS='\'''\''
+KERNEL_DIR='"$(realpath --relative-to="${PWD}" "${COMMON_FOLDER}")"'
+POST_DEFCONFIG_CMDS="check_defconfig && update_clang_config"
+CLANG_PREBUILT_BIN='"$(realpath --relative-to="${PWD}" "${CBL_USR_FOLDER}"/bin)"'
+LD_LIBRARY_PATH='"${CBL_USR_FOLDER}"'/lib
+LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN='"$(realpath --relative-to="${PWD}" "${CBL_USR_FOLDER}"/bin)"'
+FILES="
+arch/arm64/boot/Image.gz
+vmlinux
+System.map
+"
+STOP_SHIP_TRACEPRINTK=1
+
+function update_clang_config() {
+  ${KERNEL_DIR}/scripts/config --file ${OUT_DIR}/.config \
+    -e LTO_CLANG \
+    -e CFI_CLANG \
+    --set-val FRAME_WARN 2048
+  (cd ${KERNEL_DIR} && \
+    make O=${OUT_DIR} olddefconfig)
+}' > "${BUILD_CONFIG:=$(mktemp)}"
+
+    # Make path relative
+    BUILD_CONFIG=$(realpath --relative-to="${PWD}" "${BUILD_CONFIG}")
+
+    # Make sure that we are on the correct branch
+    (
+        cd "${COMMON_FOLDER}" || return
+        git ch "${BRANCH}" || { git rh -q && git ch "${BRANCH}"; }
+        git pull --rebase
+    )
+
+    # Ensure build doesn't fail with new Clang
+    sed -i 's/=hidden.*/=hidden/g' "${COMMON_FOLDER}"/Makefile
+    # SC2016: Expressions don't expand in single quotes, use double quotes for that.
+    # shellcheck disable=SC2016
+    sed -i 's/=hidden/=hidden $(call cc-option, -fsplit-lto-unit)/g' "${COMMON_FOLDER}"/Makefile
+
+    OUT_DIR=${OUT_FOLDER} BUILD_CONFIG=${BUILD_CONFIG} ./build.sh CC=clang "${@}"
+
+    git -C "${COMMON_FOLDER}" rh -q
+
+    rm "${BUILD_CONFIG}"
+)}
+
+
+# kernel/common build testing
+function kct() {(
+    # SC2031: BUILD_FOLDER was modified in a subshell. That change might be lost.
+    # shellcheck disable=SC2031
+    OUT_FOLDER=${BUILD_FOLDER}/common
+    COMMON_FOLDER=${KERNEL_FOLDER}/common
+
+    while (( ${#} )); do
+        case ${1} in
+            "-d"|"--debug") DEBUG=true ;;
+            # Show non-fatal warnings
+            "-w"|"--warnings") SHOW_NF_WARNINGS=true ;;
+        esac
+        shift
+    done
+
+    # Logging
+    LOG=$(mktemp)
+    {
+        "${CBL_USR_FOLDER}"/bin/clang --version | head -n1
+        echo
+    } > "${LOG}"
+
+    for VERSION in 4.9 4.14 4.19; do (
+        START=$(date +%s)
+
+        # Error log
+        ERRORS=$(mktemp)
+
+        # Results log
+        RESULTS=$(mktemp)
+
+        # Build kernel silently normally
+        if [[ -z ${DEBUG} ]]; then
+            kcbw "${VERSION}" KCFLAGS="${KCFLAGS:--Werror}" |& \
+            rg --color=never "error:|warning:|undefined" |& sed "s/${COMMON_FOLDER//\//\\/}\///g" > "${ERRORS}"
+        else
+            kcbw "${VERSION}" KCFLAGS="${KCFLAGS:--Werror}"
+        fi
+
+        # Make sure that if make fails, it gets propgated to the if statement
+        if [[ ${PIPESTATUS[0]} -eq 0 ]]; then
+            RESULT=successful
+        else
+            RESULT=failed
+        fi
+        TIME_STRING=$(format_time "${START}" "$(date +%s)")
+        {
+            echo "android-${VERSION} | $(git -C "${COMMON_FOLDER}" kf origin/"$(git cb)") | Build ${RESULT} in ${TIME_STRING,,}\c"
+            if [[ ${RESULT} = "successful" ]]; then
+                if KERNEL_LOCATION=${OUT_FOLDER} bootk arm64 &>/dev/null; then
+                    echo " | Boot successful\c"
+                else
+                    echo " | Boot failed\c"
+                fi
+            fi
+            echo
+        } > "${RESULTS}"
+        cat "${RESULTS}"
+        {
+            cat "${RESULTS}"
+            [[ -z ${DEBUG} && ( -n ${SHOW_NF_WARNINGS} || ${RESULT} = "failed" ) ]] && cat "${ERRORS}"
+            echo
+        } >> "${LOG}"
+        rm "${ERRORS}" "${RESULTS}"
+    ) done
+
+    MESSAGE="kernel/common build results: $(deldog "${LOG}")"
+
+    tg_msg "${MESSAGE}"
+
+    echo
+    echo "${MESSAGE}"
+    echo
+
+    rm "${LOG}"
+
 )}
