snippets/cbl: Build binutils as Arch Linux does
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/snippets/cbl b/snippets/cbl
--- a/snippets/cbl
+++ b/snippets/cbl
@@ -532,36 +532,63 @@ function bldcl() {(
 function bldbn() {(
     header "Building binutils"
     cd "${CBL_SRC_FOLDER}"/binutils || die "Error moving into ${CBL_SRC_FOLDER}/binutils"
+    BBFR=${BINUTILS_BUILD_FOLDER}
     for TUPLE in host arm-linux-gnueabi aarch64-linux-gnu powerpc-linux-gnu powerpc64le-linux-gnu; do
-        { cbf b && cd "${BINUTILS_BUILD_FOLDER}"; } || die "wtf"
+        BINUTILS_BUILD_FOLDER=${BBFR}/${TUPLE}
+        { cbf b && mkdir -p "${BINUTILS_BUILD_FOLDER}" && cd "${BINUTILS_BUILD_FOLDER}"; } || die "wtf"
         # SC2191: The = here is literal. To assign by index, use ( [index]=value ) with no spaces. To keep as literal, quote it.
         # shellcheck disable=SC2191
-        COMMON_FLAGS=( --enable-deterministic-archives
+        COMMON_FLAGS=( --prefix="${INSTALL_FOLDER:="${CBL_USR_FOLDER}"}"
+                       --enable-deterministic-archives
                        --enable-gold
+                       --enable-ld=default
                        --enable-plugins
-                       --enable-relro
-                       --disable-gdb
-                       --disable-nls
-                       --disable-sim
-                       --disable-werror
                        --quiet
-                       --with-pic
-                       --with-system-zlib
                        CFLAGS="-O2 -march=native -mtune=native"
                        CXXFLAGS="-O2 -march=native -mtune=native" )
         case ${TUPLE} in
-            "host")
-                "${CBL_SRC_FOLDER}"/binutils/configure "${COMMON_FLAGS[@]}"
+            host)
+                "${CBL_SRC_FOLDER}"/binutils/configure \
+                    --enable-lto \
+                    --enable-relro \
+                    --enable-shared \
+                    --enable-targets=x86_64-pep \
+                    --enable-threads \
+                    --disable-gdb \
+                    --disable-werror \
+                    --with-pic \
+                    --with-system-zlib \
+                    "${COMMON_FLAGS[@]}"
                 make -s configure-host V=0 ;;
-            *)
-                "${CBL_SRC_FOLDER}"/binutils/configure --target=${TUPLE} \
-                                                       --program-prefix=${TUPLE}- \
-                                                       "${COMMON_FLAGS[@]}" ;;
+            arm-*|aarch64-*)
+                "${CBL_SRC_FOLDER}"/binutils/configure \
+                    --disable-multilib \
+                    --disable-nls \
+                    --program-prefix=${TUPLE}- \
+                    --target=${TUPLE} \
+                    --with-gnu-as \
+                    --with-gnu-ld \
+                    --with-sysroot="${INSTALL_FOLDER}/${TUPLE}" \
+                    "${COMMON_FLAGS[@]}" ;;
+            powerpc*)
+                "${CBL_SRC_FOLDER}"/binutils/configure \
+                    --enable-lto \
+                    --enable-relro \
+                    --enable-shared \
+                    --enable-threads \
+                    --disable-gdb \
+                    --disable-sim \
+                    --disable-werror \
+                    --program-prefix=${TUPLE}- \
+                    --target=${TUPLE} \
+                    --with-pic \
+                    --with-system-zlib \
+                    "${COMMON_FLAGS[@]}" ;;
         esac
         time make -s "${JOBS_FLAG}" V=0 || die "Error building ${TARGET} binutils"
         # SC2031: INSTALL_FOLDER was modified in a subshell. That change might be lost.
         # shellcheck disable=SC2031
-        make -s prefix="${INSTALL_FOLDER:="${CBL_USR_FOLDER}"}" install V=0 || die "Error installing ${TARGET} binutils"
+        [[ "${1}" =~ "-i" ]] && { make -s prefix="${INSTALL_FOLDER}" install V=0 || die "Error installing ${TARGET} binutils"; }
         cd ..
     done
 )}
@@ -599,5 +626,5 @@ function bldusr() {(
     bldcl -i
 
     # Build binutils
-    bldbn
+    bldbn -i
 )}
