snippets/cbl: Break out the Clang/lld building part into its own function and some slight refractor
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/snippets/cbl b/snippets/cbl
--- a/snippets/cbl
+++ b/snippets/cbl
@@ -283,39 +283,16 @@ function cbldckr() {
     docker run --privileged --rm -ti nathanchance/cbl
 }
 
-
-# Build Clang, lld. and arm{32,64} and powerpc binutils from source
-function cblbinaries() {(
-    CBL=${HOME}/cbl
-    INSTALL_FOLDER=${CBL}/prebuilt
-
-    # Update/clone LLVM/Clang
-    if [[ ! -d ${CBL}/llvm ]]; then
-        git -C "${CBL}" clone --single-branch -b master https://git.llvm.org/git/llvm.git
-        git -C "${CBL}" clone --single-branch -b master https://git.llvm.org/git/clang.git llvm/tools/clang
-        git -C "${CBL}" clone --single-branch -b master https://git.llvm.org/git/lld.git llvm/tools/lld
-    else
-        for FOLDER in llvm llvm/tools/clang llvm/tools/lld; do
-            git -C "${CBL}/${FOLDER}" pull --rebase || die "Error updating ${FOLDER}!"
-        done
-    fi
-
-    # Update/clone binutils
-    if [[ ! -d ${CBL}/binutils ]]; then
-        git -C "${CBL}" clone --single-branch -b master git://sourceware.org/git/binutils-gdb.git binutils
-    else
-        git -C "${CBL}"/binutils pull --rebase || die "Error updating ${CBL}/binutils"
-    fi
-
-    # Build Clang and lld
-    { cd "${CBL}" && rm -rf llvm/build && mkdir -p llvm/build && cd llvm/build; } || die "wtf"
+# Build Clang
+function cblclang() {(
+    { cd "${CBL_FOLDER}" && rm -rf llvm/build && mkdir -p llvm/build && cd llvm/build; } || die "wtf"
     cmake -G Ninja -DCMAKE_BUILD_TYPE=Release \
                    -DCMAKE_C_COMPILER=clang \
                    -DCMAKE_C_FLAGS="-O2 -march=native -mtune=native" \
                    -DCMAKE_CXX_COMPILER=clang++ \
                    -DCMAKE_CXX_FLAGS="-O2 -march=native -mtune=native" \
-                   -DCMAKE_INSTALL_PREFIX="${INSTALL_FOLDER}" \
-                   -DLLVM_BINUTILS_INCDIR="${CBL}/binutils/include" \
+                   -DCMAKE_INSTALL_PREFIX="${INSTALL_FOLDER:+"${CBL_FOLDER}/prebuilt"}" \
+                   -DLLVM_BINUTILS_INCDIR="${CBL_FOLDER}/binutils/include" \
                    -DLLVM_ENABLE_BINDINGS=OFF \
                    -DLLVM_CCACHE_BUILD=ON \
                    -DLLVM_ENABLE_OCAMLDOC=OFF \
@@ -326,11 +303,36 @@ function cblbinaries() {(
                    -DLLVM_TARGETS_TO_BUILD="ARM;AArch64;PowerPC;X86" \
                    -DLLVM_USE_LINKER=lld ..
     time ninja || die "Error building Clang/lld!"
+)}
+
+# Build Clang, lld. and arm{32,64} and powerpc binutils from source
+function cblbinaries() {(
+    # Update/clone LLVM/Clang
+    if [[ ! -d ${CBL_FOLDER}/llvm ]]; then
+        git -C "${CBL_FOLDER}" clone --single-branch -b master https://git.llvm.org/git/llvm.git
+        git -C "${CBL_FOLDER}" clone --single-branch -b master https://git.llvm.org/git/clang.git llvm/tools/clang
+        git -C "${CBL_FOLDER}" clone --single-branch -b master https://git.llvm.org/git/lld.git llvm/tools/lld
+    else
+        for REPO_FOLDER in llvm llvm/tools/clang llvm/tools/lld; do
+            git -C "${CBL_FOLDER}/${REPO_FOLDER}" pull --rebase || die "Error updating ${REPO_FOLDER}!"
+        done
+    fi
+
+    # Update/clone binutils
+    if [[ ! -d ${CBL_FOLDER}/binutils ]]; then
+        git -C "${CBL_FOLDER}" clone --single-branch -b master git://sourceware.org/git/binutils-gdb.git binutils
+    else
+        git -C "${CBL_FOLDER}"/binutils pull --rebase || die "Error updating ${CBL_FOLDER}/binutils"
+    fi
+
+    # Build Clang and lld
+    INSTALL_FOLDER=${CBL_FOLDER}/prebuilt
+    cblclang
     rm -rf "${INSTALL_FOLDER}"
-    ninja install || die "Error installing Clang/lld!"
+    ninja -C "${CBL_FOLDER}/llvm/build" install || die "Error installing Clang/lld!"
 
     # Build binutils
-    cd "${CBL}"/binutils || die "Error moving into ${CBL}/binutils"
+    cd "${CBL_FOLDER}"/binutils || die "Error moving into ${CBL_FOLDER}/binutils"
     for TUPLE in arm-linux-gnueabi aarch64-linux-gnu powerpc-linux-gnu; do
         { rm -rf out && mkdir out && cd out; } || die "wtf"
         ../configure --target=${TUPLE} \
@@ -348,7 +350,7 @@ function cblbinaries() {(
                      CFLAGS="-O2 -march=native -mtune=native" \
                      CXXFLAGS="-O2 -march=native -mtune=native"
         time make "${JOBS_FLAG}" || die "Error building ${TARGET} binutils"
-        make prefix="${CBL}/prebuilt" install || die "Error installing ${TARGET} binutils"
+        make prefix="${INSTALL_FOLDER}" install || die "Error installing ${TARGET} binutils"
         cd ..
     done
 )}
