env: Undo removal of subshells
Pure prompt has a regression.

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/env/stubs/cbl b/env/stubs/cbl
--- a/env/stubs/cbl
+++ b/env/stubs/cbl
@@ -530,42 +530,35 @@ function babk() { (
 
 # Show local LLVM patches via git log
 function llvm_log() {
-    local llvm_proj mlfc
+    local LLVM_PROJ=${TCBLD:?}/llvm-project
 
-    llvm_proj=${TCBLD:?}/llvm-project
-    mlfc=$(git -C "${llvm_proj}" mfc)
-
-    if [[ -n ${mlfc} ]]; then
+    MLFC=$(git -C "${LLVM_PROJ}" mfc)
+    if [[ -n ${MLFC} ]]; then
         echo
         echo "LLVM commit log:"
         echo
-        git -C "${llvm_proj}" lo "${mlfc}"^^..HEAD
+        git -C "${LLVM_PROJ}" lo "${MLFC}"^^..HEAD
     fi
 }
 
 # linux testing
-function lt() {
-    local blocklist _krnl_dir log_dir mfc msg _tc_dir tc_bld_args
+function lt() { (
+    : "${KRNL_DIR:=${CBL_KERNELS}/${TREE:=linux-next}}"
+    LOG_DIR=${CBL}/build-logs/${KRNL_DIR##*/}-$(date +%Y%m%d-%H%M)
+    mkdir -p "${LOG_DIR}"
 
-    _krnl_dir=${KRNL_DIR:-${CBL_KERNELS}/${TREE:-linux-next}}
-    _tc_dir=${TC_DIR:-${CBL_LLVM_BNTL%/*}}
-
-    log_dir=${CBL}/build-logs/${_krnl_dir##*/}-$(date +%Y%m%d-%H%M)
-
-    mkdir -p "${log_dir}"
-
-    [[ ${_krnl_dir##*/} = "linux" ]] && tc_bld_args=(--test-lto-cfi-kernel)
+    [[ ${KRNL_DIR##*/} = "linux" ]] && TC_BLD_ARGS=(--test-lto-cfi-kernel)
     "${CBL}"/llvm-kernel-testing/test.sh \
-        --linux-src "${_krnl_dir}" \
-        --log-dir "${log_dir}" \
+        --linux-src "${KRNL_DIR}" \
+        --log-dir "${LOG_DIR}" \
         --skip-tc-build \
-        --tc-prefix "${_tc_dir}" \
-        "${tc_bld_args[@]}" || return ${?}
+        --tc-prefix "${TC_DIR:=${CBL_LLVM_BNTL%/*}}" \
+        "${TC_BLD_ARGS[@]}" || die "llvm-kernel-testing failed (${?})"
 
     {
         echo "Host: $(uname -n)"
         echo
-        cat "${log_dir}"/results.log
+        cat "${LOG_DIR}"/results.log
         echo
         echo "Full warning report:"
         echo
@@ -575,29 +568,29 @@ function lt() {
         # objtool: Too many to deal with for now
         # results.log: Any warnings from this will be in the other logs
         # same module names found: Kbuild warnings that are not a result of clang
-        blocklist="arch/powerpc/boot/inffast.c|arch/powerpc/boot/main.c|being placed in|DWARF2 only supports one section per compilation unit|objtool:|results.log|same module names found"
-        rg "error:|FATAL:|undefined|warning:|WARNING:" "${log_dir}"/*.log |& rg -v -- "${blocklist}" |& sed 's/.*.log://g' |& cut -d / -f 7- |& sort |& uniq
-        mfc=$(git -C "${_krnl_dir}" mfc)
-        if [[ -n ${mfc} ]]; then
+        BLOCKLIST="arch/powerpc/boot/inffast.c|arch/powerpc/boot/main.c|being placed in|DWARF2 only supports one section per compilation unit|objtool:|results.log|same module names found"
+        rg "error:|FATAL:|undefined|warning:|WARNING:" "${LOG_DIR}"/*.log |& rg -v -- "${BLOCKLIST}" |& sed 's/.*.log://g' |& cut -d / -f 7- |& sort |& uniq
+        MFC=$(git -C "${KRNL_DIR}" mfc)
+        if [[ -n ${MFC} ]]; then
             echo
-            echo "${_krnl_dir##*/} commit log:"
+            echo "${KRNL_DIR##*/} commit log:"
             echo
-            git -C "${_krnl_dir}" lo "${mfc}"^^..HEAD
+            git -C "${KRNL_DIR}" lo "${MFC}"^^..HEAD
         fi
         llvm_log
-    } >"${log_dir}"/deldog.log
+    } >"${LOG_DIR}"/deldog.log
 
-    msg="${log_dir##*/} build results: $(deldog "${log_dir}/deldog.log")"
+    MESSAGE="${LOG_DIR##*/} build results: $(deldog "${LOG_DIR}/deldog.log")"
 
-    tg_msg "${msg}"
+    tg_msg "${MESSAGE}"
 
     echo
-    echo "${msg}"
-    echo "Full logs available at: ${log_dir}"
+    echo "${MESSAGE}"
+    echo "Full logs available at: ${LOG_DIR}"
     echo
 
-    rm "${log_dir}"/deldog.log
-}
+    rm "${LOG_DIR}"/deldog.log
+); }
 
 # Pull the latest CBL Docker image and run it with podman
 function pdmnrn() { (
@@ -611,69 +604,64 @@ function pdmnrn() { (
 ); }
 
 # Strip executables within a folder
-function stripall() {
-    local file
-    for file in $(fd -t file "${1:?}" -x file | grep 'not stripped' | cut -d: -f1); do strip "${file}"; done
-}
+function stripall() { (
+    cd "${1:?}"
+    for FILE in $(fd -t file -x file | grep 'not stripped' | cut -d: -f1); do strip "${FILE}"; done
+); }
 
 # Build LLVM
-function bldllvm() {
+function bldllvm() { (
     # Setup ccache
     ccache_size llvm 75
 
     "${TCBLD}"/build-llvm.py "${@}"
-    local exit_code=${?}
-    unset CCACHE_DIR
-    return ${exit_code}
-}
+); }
 
 # Build binutils
-function bldbn() {
+function bldbn() { (
     # Setup ccache
     ccache_size binutils 25
 
     "${TCBLD}"/build-binutils.py "${@}"
-    local exit_code=${?}
-    unset CCACHE_DIR
-    return ${exit_code}
-}
+); }
 
 # Build LLVM/Clang/lld and arm{32,64} and powerpc binutils from source
-function bldtcs() {
-    local bldbn_install_folder bldllvm_install_folder date_time exit_code tc_bld_bntls tc_bld_llvm_prjct
-
-    date_time=$(date +%Y%m%d-%H%M)
+function bldtcs() { (
+    DATE_TIME=$(date +%Y%m%d-%H%M)
 
     # Build binutils
-    tc_bld_bntls=${TCBLD}/binutils
-    [[ -d ${tc_bld_bntls} ]] || git clone https://sourceware.org/git/binutils-gdb.git "${tc_bld_bntls}"
-    git -C "${tc_bld_bntls}" pull --rebase || { EXIT=false die "Updating binutils failed (${?})" && return 1; }
-    bldbn_install_folder=${CBL_TC}/binutils-${date_time}-$(git -C "${tc_bld_bntls}" sh -s --format=%H origin/master)
+    TC_BLD_BNTLS=${TCBLD}/binutils
+    [[ -d ${TC_BLD_BNTLS} ]] || git clone https://sourceware.org/git/binutils-gdb.git "${TC_BLD_BNTLS}"
+    git -C "${TC_BLD_BNTLS}" pull --rebase || die "Updating binutils failed (${?})"
+    BLDBN_INSTALL_FOLDER=${CBL_TC}/binutils-${DATE_TIME}-$(git -C "${TC_BLD_BNTLS}" sh -s --format=%H origin/master)
     bldbn \
         --build-folder "${BBF:?}" \
-        --install-folder "${bldbn_install_folder}" || { EXIT=false die "bldbn failed (${?})" && return 1; }
-    stripall "${bldbn_install_folder}"
+        --install-folder "${BLDBN_INSTALL_FOLDER}" || die "bldbn failed with exit code ${?}"
+    stripall "${BLDBN_INSTALL_FOLDER}"
 
     # Update binutils
-    rm -f "${CBL_BNTL%/*}" &&
-        ln -rs "${bldbn_install_folder}" "${CBL_BNTL%/*}"
+    (cd "${CBL_TC}" &&
+        rm -f binutils &&
+        ln -s "${BLDBN_INSTALL_FOLDER##*/}" binutils)
 
     # Build LLVM/Clang/lld
-    tc_bld_llvm_prjct=${TCBLD}/llvm-project
-    [[ -d ${tc_bld_llvm_prjct} ]] || git clone https://github.com/llvm/llvm-project "${tc_bld_llvm_prjct}"
-    git -C "${tc_bld_llvm_prjct}" pull --rebase || { EXIT=false die "Updating llvm-project failed (${?})" && return 1; }
-    bldllvm_install_folder=${CBL_TC}/llvm-${date_time}-$(git -C "${tc_bld_llvm_prjct}" sh -s --format=%H origin/master)
+    TC_BLD_LLVM_PRJCT=${TCBLD}/llvm-project
+    [[ -d ${TC_BLD_LLVM_PRJCT} ]] || git -C "${TCBLD}" clone https://github.com/llvm/llvm-project
+    git -C "${TC_BLD_LLVM_PRJCT}" pull --rebase || die "Updating llvm-project failed (${?})"
+    BLDLLVM_INSTALL_FOLDER=${CBL_TC}/llvm-${DATE_TIME}-$(git -C "${TC_BLD_LLVM_PRJCT}" sh -s --format=%H origin/master)
     bldllvm \
         --assertions \
         --build-folder "${LBF:?}" \
         --check-targets lld clang llvm \
-        --install-folder "${bldllvm_install_folder}" \
+        --install-folder "${BLDLLVM_INSTALL_FOLDER}" \
         --lto=thin \
-        --pgo || { EXIT=false die "bldllvm failed with exit code ${?}" && return 1; }
-    stripall "${bldllvm_install_folder}"
+        --pgo || die "bldllvm failed with exit code ${?}"
+    stripall "${BLDLLVM_INSTALL_FOLDER}"
 
-    rm -f "${CBL_LLVM%/*}" &&
-        ln -rs "${bldllvm_install_folder}" "${CBL_LLVM%/*}"
+    # Update llvm-tot symlink
+    (cd "${CBL_TC}" &&
+        rm -f llvm-tot &&
+        ln -sf "${BLDLLVM_INSTALL_FOLDER##*/}" llvm-tot)
 
     # Combine CBL_LLVM and CBL_BNTL for llvm-kernel-testing
     rm -rf "${CBL_LLVM_BNTL%/*}" &&
@@ -683,7 +671,7 @@ function bldtcs() {
 
     # Invalidate our kernel ccache because we have a new compiler that will be used for it
     ccache_clear kernel
-}
+); }
 
 # Switch cuttlefish branch
 function switch_kc_branch() { (
@@ -920,19 +908,19 @@ function kct() { (
 
 # Build all kernel trees
 function bldallk() {
-    local tree
+    local TREE
 
-    for tree in linux{,-next,-stable}; do TREE=${tree} lt; done
-    # kct ""
+    for TREE in linux{,-next,-stable}; do TREE=${TREE} lt ""; done
+    kct ""
     "${CBL_KERNELS}"/rpi/bin/build.sh
     "${CBL_KERNELS}"/wsl2/bin/build.sh
 }
 
 # Build new LLVM/Clang/lld and test all kernel trees
-function bldall() {
-    TG=true bldtcs &&
-        bldallk
-}
+function bldall() { (
+    export TG=true
+    bldtcs && bldallk
+); }
 
 # Function to test build-{binutils,llvm}.py in multiple Docker images
 function bld_llvm_bntls_py() { (
