env/stubs/updbin: Move away from deb packages
Signed-off-by: Nathan Chancellor <nathan@kernel.org>

diff --git a/env/stubs/updbin b/env/stubs/updbin
--- a/env/stubs/updbin
+++ b/env/stubs/updbin
@@ -581,17 +581,23 @@ function birg() { (
     [[ -z ${RG_VERSION} ]] && RG_VERSION=$(glr "${RG_REPO}")
     BASE_URL=https://github.com/${RG_REPO}
 
-    if [[ $(uname -m) = "x86_64" ]] && command -v dpkg &>/dev/null; then
+    if [[ $(uname -m) = "x86_64" ]]; then
         header "Installing ripgrep"
 
-        DEB=ripgrep_${RG_VERSION}_amd64.deb
+        RG_STOW=${PREFIX:-${USR_FOLDER:?}}/stow
+        RG_BIN=${RG_STOW}/prebuilts/bin
+        RG_TAR=ripgrep-${RG_VERSION}-x86_64-unknown-linux-musl.tar.gz
 
         TMP_FOLDER=$(mktemp -d)
-        cd "${TMP_FOLDER}"
+        cd "${TMP_FOLDER}" || exit ${?}
 
-        curl -LSsO "${BASE_URL}"/releases/download/"${RG_VERSION}"/"${DEB}" || die "Error downloading ${DEB}"
-        sudo dpkg -i "${DEB}" || die "Error installing ${DEB}"
-        cd && rm -rf "${TMP_FOLDER}"
+        curl -LSs "${BASE_URL}"/releases/download/"${RG_VERSION}"/"${RG_TAR}" | tar -xzf - || die "Error downloading ${RG_TAR}"
+        cd "${RG_TAR%.tar.gz}" || exit ${?}
+        install -Dm755 rg "${RG_BIN}"/rg
+
+        stow -d "${RG_STOW}" -R -v prebuilts
+
+        move_to_front_of_path "${RG_STOW%/*}"/bin
     else
         header "Building ripgrep"
 
@@ -608,8 +614,9 @@ function birg() { (
         cd "${RG_SRC}" || die "Error downloading ripgrep source"
         cargo build --release --locked --features 'pcre2' || die "cargo build failed"
         cargo install --force --path . || die "cargo install failed"
-        [[ -n ${ZSH_NAME} ]] && install -Dm644 complete/_rg "${HOME}"/.zfunctions/_rg
     fi
+    [[ -n ${ZSH_NAME} ]] && install -Dm644 complete/_rg "${HOME}"/.zfunctions/_rg
+    [[ -n ${TMP_FOLDER} ]] && cd && rm -rf "${TMP_FOLDER}"
 
     command -v rg
     rg --version
@@ -637,9 +644,25 @@ function bisharkdp() { (
         if [[ $(uname -m) = "x86_64" ]] && command -v dpkg &>/dev/null; then
             header "Installing ${BINARY}"
 
-            DEB=${TMP_FOLDER}/${BINARY}_${BIN_VERSION//v/}_amd64.deb
-            curl -LSso "${DEB}" "${URL_BASE}"/releases/download/"${BIN_VERSION}"/"${DEB##*/}" || die "Error downloading ${DEB##*/}"
-            sudo dpkg -i "${DEB}" || die "Error installing ${DEB##*/}"
+            BINARY_STOW=${PREFIX:-${USR_FOLDER:?}}/stow
+            BINARY_BIN=${BINARY_STOW}/prebuilts/bin
+            BINARY_TAR=${BINARY}-${BIN_VERSION}-x86_64-unknown-linux-gnu.tar.gz
+
+            cd "${TMP_FOLDER}" || exit ${?}
+            curl -LSs "${URL_BASE}"/releases/download/"${BIN_VERSION}"/"${BINARY_TAR}" | tar -xzf - || die "Error downloading ${BINARY_TAR}"
+            cd "${BINARY_TAR%.tar.gz}" || exit ${?}
+            install -Dm755 "${BINARY}" "${BINARY_BIN}"/"${BINARY}"
+            if [[ -n ${ZSH_NAME} ]]; then
+                case ${BINARY} in
+                    bat) BINARY_AUTOCOMP=${BINARY}.zsh ;;
+                    fd | hyperfine) BINARY_AUTOCOMP=_${BINARY} ;;
+                esac
+                [[ -n ${BINARY_AUTOCOMP} ]] && install -Dm644 autocomplete/"${BINARY_AUTOCOMP}" "${HOME}"/.zfunctions/_"${BINARY}"
+            fi
+
+            stow -d "${BINARY_STOW}" -R -v prebuilts
+
+            move_to_front_of_path "${BINARY_STOW%/*}"/bin
         else
             header "Building ${BINARY}"
 
@@ -663,10 +686,10 @@ function bisharkdp() { (
                     fd) install -Dm644 target/release/build/fd-find-*/out/_fd "${HOME}"/.zfunctions/_fd ;;
                 esac
             fi
+            move_to_front_of_path "${HOME}/.cargo/bin"
         fi
 
         # Print information about new binary
-        move_to_front_of_path "${HOME}/.cargo/bin"
         command -v "${BINARY}"
         "${BINARY}" --version
     ); done
