build-clang: Fix error detection logic
The error statement should only fire on git clone's error code, not the
conditional's.

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/build-clang b/build-clang
--- a/build-clang
+++ b/build-clang
@@ -152,7 +152,9 @@ function git_sync() {(
     fi
 
     # If folder doesn't exist, we need to clone it
-    [[ ! -d ${FOLDER} ]] && git clone "${URL}" -b "${BRANCH}" "${FOLDER}" || die "Error cloning ${FOLDER}!"
+    if [[ ! -d ${FOLDER} ]]; then
+        git clone "${URL}" -b "${BRANCH}" "${FOLDER}" || die "Error cloning ${FOLDER}!"
+    fi
 
     cd "${FOLDER}" || die "Error moving into ${FOLDER}"
 
