build-clang: Account for the possibility of local patches
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/build-clang b/build-clang
--- a/build-clang
+++ b/build-clang
@@ -188,7 +188,7 @@ function git_sync() {(
         fi
     else
         git fetch origin || die "There was an error fetching updates for ${FOLDER}!"
-        git reset --hard origin/"${BRANCH}" || die "There was an error updating ${FOLDER}!"
+        git rebase origin/"${BRANCH}" || die "There was an error updating ${FOLDER}!"
     fi
 
     # Roll back if necessary
