downstream-als-merge: Add some Franco Kernels and add some more failure points
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/downstream-als-merge b/downstream-als-merge
--- a/downstream-als-merge
+++ b/downstream-als-merge
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# Pull in android-linux-stable updates to various ROM kernel trees
+# Pull in android-linux-stable updates to various ROM and custom kernel trees
 #
 # Copyright (C) 2018 Nathan Chancellor
 #
@@ -19,57 +19,114 @@
 
 
 source common
-KERNELS_HOME=${HOME}/kernels/roms
+ROMS_HOME=${HOME}/kernels/roms
+FRANCO_HOME=${HOME}/kernels/franco
 
 
 
 
-# AICP OnePlus 5
-cd "${KERNELS_HOME}/aicp-op5" || die "aicp-op5 does not exist, please clone!"
+# AICP OnePlus 5 (downstream of op5)
+cd "${ROMS_HOME}/aicp-op5" || die "aicp-op5 does not exist, please clone!"
 CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
 git fetch origin
 git reset --hard origin/"${CURRENT_BRANCH}"
 git fetch aicp
 git ml --no-edit aicp/o8.1 || die "Merge conflicts detected, please resolve then continue!"
-git fetch als
+git fetch als || die "android-linux-stable remote doesn't exist, please add then continue!"
 git ml --no-edit als/lineage-15.1 || die "Merge conflicts detected, please resolve then continue!"
-git push -f origin HEAD:"${CURRENT_BRANCH}"
+git push -f origin HEAD:"${CURRENT_BRANCH}" || die "Can't push source to fork!"
 
 
 
 
-# AOSiP Essential Phone
-cd "${KERNELS_HOME}/aosip-mata" || die "aosip-mata does not exist, please clone!"
+# AOSiP Essential Phone (downstream of mata)
+cd "${ROMS_HOME}/aosip-mata" || die "aosip-mata does not exist, please clone!"
 CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
 git fetch origin
 git reset --hard origin/"${CURRENT_BRANCH}"
-git fetch als
+git fetch als || die "android-linux-stable remote doesn't exist, please add then continue!"
 git ml --no-edit als/lineage-15.1 || die "Merge conflicts detected, please resolve then continue!"
-git push -f nathanchance HEAD:"${CURRENT_BRANCH}"
+git push -f nathanchance HEAD:"${CURRENT_BRANCH}" || die "Can't push source to fork!"
 hub pull-request -b "${CURRENT_BRANCH}" -m "Merge $(make kernelversion) into ${CURRENT_BRANCH}"
 
 
 
 
-# GZR OnePlus 3
-cd "${KERNELS_HOME}/gzr-op3" || die "gzr-op3 does not exist, please clone!"
+# Franco Kernel Mido (downstream of msm-3.18)
+cd "${FRANCO_HOME}/mido" || die "mido does not exist, please clone!"
+CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+git fetch origin
+git ml --no-edit origin/"${CURRENT_BRANCH}" || die "Merge conflicts detected, please resolve then continue!"
+git fetch als || die "android-linux-stable remote doesn't exist, please add then continue!"
+git ml --no-edit als/kernel.lnx.3.18.r33-rel || die "Merge conflicts detected, please resolve then continue!"
+git push -f nathanchance HEAD:"${CURRENT_BRANCH}" || die "Can't push source to fork!"
+
+
+
+
+# Franco Kernel OP3 (downstream of op3)
+cd "${FRANCO_HOME}/op3" || die "op3 does not exist, please clone!"
+CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+git fetch origin
+git ml --no-edit origin/"${CURRENT_BRANCH}" || die "Merge conflicts detected, please resolve then continue!"
+git fetch als || die "android-linux-stable remote doesn't exist, please add then continue!"
+git ml --no-edit als/oneplus/QC8996_O_8.0.0 || die "Merge conflicts detected, please resolve then continue!"
+git push -f nathanchance HEAD:"${CURRENT_BRANCH}" || die "Can't push source to fork!"
+
+
+
+
+# Franco Kernel OP5 (on its own)
+cd "${FRANCO_HOME}/op5" || die "op5 does not exist, please clone!"
+for BRANCH in oreo oreo-mr1; do
+    git ch ${BRANCH}
+    git fetch origin
+    git ml --no-edit origin/"${BRANCH}" || die "Merge conflicts detected, please resolve then continue!"
+
+    merge-stable
+    for FILE in $(git cf); do
+        git rf "${FILE}"
+    done
+    git ap -3 "${ALS_PATCHES}/4.4.125/mmu.c"
+    git fm
+
+    git push -f nathanchance HEAD:"${CURRENT_BRANCH}" || die "Can't push source to fork!"
+done
+
+
+
+
+# Franco Kernel Tissot (downstream of tissot)
+cd "${FRANCO_HOME}/tissot" || die "tissot does not exist, please clone!"
+CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+git fetch origin
+git ml --no-edit origin/"${CURRENT_BRANCH}" || die "Merge conflicts detected, please resolve then continue!"
+git fetch als || die "android-linux-stable remote doesn't exist, please add then continue!"
+git ml --no-edit als/tissot-o-oss || die "Merge conflicts detected, please resolve then continue!"
+git push -f nathanchance HEAD:"${CURRENT_BRANCH}" || die "Can't push source to fork!"
+
+
+
+
+# GZR OnePlus 3 (downstream of op3)
+cd "${ROMS_HOME}/gzr-op3" || die "gzr-op3 does not exist, please clone!"
 CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
 git fetch origin
 git reset --hard origin/"${CURRENT_BRANCH}"
-git fetch als
+git fetch als || die "android-linux-stable remote doesn't exist, please add then continue!"
 git ml --no-edit als/lineage-15.1 || die "Merge conflicts detected, please resolve then continue!"
-git push -f nathanchance HEAD:"${CURRENT_BRANCH}"
+git push -f nathanchance HEAD:"${CURRENT_BRANCH}" || die "Can't push source to fork!"
 hub pull-request -b "${CURRENT_BRANCH}" -m "Merge $(make kernelversion) into ${CURRENT_BRANCH}"
 
 
 
 
-# GZR OnePlus 5
-cd "${KERNELS_HOME}/gzr-op5" || die "gzr-op5 does not exist, please clone!"
+# GZR OnePlus 5 (downstream of op5)
+cd "${ROMS_HOME}/gzr-op5" || die "gzr-op5 does not exist, please clone!"
 CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
 git fetch origin
 git reset --hard origin/"${CURRENT_BRANCH}"
-git fetch als
+git fetch als || die "android-linux-stable remote doesn't exist, please add then continue!"
 git ml --no-edit als/lineage-15.1 || die "Merge conflicts detected, please resolve then continue!"
-git push -f nathanchance HEAD:"${CURRENT_BRANCH}"
+git push -f nathanchance HEAD:"${CURRENT_BRANCH}" || die "Can't push source to fork!"
 hub pull-request -b "${CURRENT_BRANCH}" -m "Merge $(make kernelversion) into ${CURRENT_BRANCH}"
