als-merge: Update
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/downstream-als-merge b/downstream-als-merge
--- a/downstream-als-merge
+++ b/downstream-als-merge
@@ -30,7 +30,7 @@ FRANCO_HOME=${HOME}/kernels/franco
 if [[ "$*" =~ "3.18" ]]; then
     # Franco Kernel Mido (downstream of msm-3.18)
     cd "${FRANCO_HOME}/mido" || die "mido does not exist, please clone!"
-    CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+    CURRENT_BRANCH=$(git cb)
     git fetch origin
     git ml --no-edit origin/"${CURRENT_BRANCH}" || die "Merge conflicts detected, please resolve then continue!"
     git fetch als || die "android-linux-stable remote doesn't exist, please add then continue!"
@@ -42,7 +42,7 @@ if [[ "$*" =~ "3.18" ]]; then
 
     # Franco Kernel OP3 (downstream of op3)
     cd "${FRANCO_HOME}/op3" || die "op3 does not exist, please clone!"
-    CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+    CURRENT_BRANCH=$(git cb)
     git fetch origin
     git ml --no-edit origin/"${CURRENT_BRANCH}" || die "Merge conflicts detected, please resolve then continue!"
     git fetch als || die "android-linux-stable remote doesn't exist, please add then continue!"
@@ -54,11 +54,20 @@ if [[ "$*" =~ "3.18" ]]; then
 
     # Franco Kernel Tissot (downstream of tissot)
     cd "${FRANCO_HOME}/tissot" || die "tissot does not exist, please clone!"
-    CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+    git checkout oreo
+    CURRENT_BRANCH=$(git cb)
     git fetch origin
     git ml --no-edit origin/"${CURRENT_BRANCH}" || die "Merge conflicts detected, please resolve then continue!"
     git fetch als || die "android-linux-stable remote doesn't exist, please add then continue!"
     git ml --no-edit als/tissot-o-oss || die "Merge conflicts detected, please resolve then continue!"
+    git push -f nathanchance HEAD:"${CURRENT_BRANCH}" || die "Can't push source to fork!"
+
+    git checkout oreo-mr1
+    CURRENT_BRANCH=$(git cb)
+    git fetch origin
+    git ml --no-edit origin/"${CURRENT_BRANCH}" || die "Merge conflicts detected, please resolve then continue!"
+    merge-stable
+    [[ -f ${SCRIPTS_FOLDER}/als-patches/3.18.103/fk-tissot-commands ]] && bash ${SCRIPTS_FOLDER}/als-patches/3.18.103/fk-tissot-commands
     git push -f nathanchance HEAD:"${CURRENT_BRANCH}" || die "Can't push source to fork!"
 
 
@@ -66,7 +75,7 @@ if [[ "$*" =~ "3.18" ]]; then
 
     # GZR OnePlus 3 (downstream of op3)
     cd "${ROMS_HOME}/gzr-op3" || die "gzr-op3 does not exist, please clone!"
-    CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+    CURRENT_BRANCH=$(git cb)
     git fetch origin
     git reset --hard origin/"${CURRENT_BRANCH}"
     git fetch als || die "android-linux-stable remote doesn't exist, please add then continue!"
@@ -82,7 +91,7 @@ fi
 if [[ "$*" =~ "4.4" ]]; then
     # AICP OnePlus 5 (downstream of op5)
     cd "${ROMS_HOME}/aicp-op5" || die "aicp-op5 does not exist, please clone!"
-    CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+    CURRENT_BRANCH=$(git cb)
     git fetch origin
     git reset --hard origin/"${CURRENT_BRANCH}"
     git fetch aicp
@@ -96,7 +105,7 @@ if [[ "$*" =~ "4.4" ]]; then
 
     # AOSiP Essential Phone (downstream of mata)
     cd "${ROMS_HOME}/aosip-mata" || die "aosip-mata does not exist, please clone!"
-    CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+    CURRENT_BRANCH=$(git cb)
     git fetch origin
     git reset --hard origin/"${CURRENT_BRANCH}"
     git fetch als || die "android-linux-stable remote doesn't exist, please add then continue!"
@@ -109,7 +118,7 @@ if [[ "$*" =~ "4.4" ]]; then
 
     # GZR OnePlus 5 (downstream of op5)
     cd "${ROMS_HOME}/gzr-op5" || die "gzr-op5 does not exist, please clone!"
-    CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+    CURRENT_BRANCH=$(git cb)
     git fetch origin
     git reset --hard origin/"${CURRENT_BRANCH}"
     git fetch als || die "android-linux-stable remote doesn't exist, please add then continue!"
