Upstream: Update to the version I did for DU
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/upstream b/upstream
--- a/upstream
+++ b/upstream
@@ -18,40 +18,85 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>
 
 
-# SOURCE OUR UNIVERSAL FUNCTIONS SCRIPT AND MAC CHECK
+# Source our universal functions script and Mac check
 source common
 
+# Parse the provided parameters
+function parse_parameters() {
+    while [[ $# -ge 1 ]]; do
+        case ${1} in
+            # Use git cherry-pick
+            "-cp"|"--cherry-pick")
+                export UPDATE_METHOD=cherry-pick ;;
 
-# GATHER PARAMETERS
-while [[ $# -ge 1 ]]; do
-    case ${1} in
-        # MERGE VERSION INSTEAD OF CHERRY-PICK
-        "-m"|"--merge")
-            MERGE=true ;;
+            # Help menu
+            "-h"|"--help")
+                echo
+                echo "${BOLD}Script description:${RST} Merges/cherry-picks Linux upstream into a kernel tree"
+                echo
+                echo "${BOLD}Required parameters:${RST}"
+                echo "    -cp | --cherry-pick"
+                echo "    -mg | --merge"
+                echo "        Call either git cherry-pick or git merge when updating from upstream"
+                echo
+                echo "${BOLD}Optional parameters"
+                echo "    -pl | --print-latest"
+                echo "        Prints the latest version available for the current kernel tree upstream then exits"
+                echo
+                echo "    -u  | --update-only"
+                echo "        Simply fetches the linux-stable and linux-stable-rc remotes then exits"
+                echo
+                echo "    -ul | --update-latest"
+                echo "        Updates to the latest version available for the current kernel tree upstream"
+                echo
+                echo "    -v  | --version"
+                echo "        Updates to the specified version (e.g. -v 3.18.78)"
+                echo
+                echo "${BOLD}Notes:${RST}"
+                echo "    1. By default, only ONE version is picked at a time (e.g. 3.18.31 to 3.18.32)"
+                echo "    2. If you already have a remote for upstream, rename it to linux-stable so that multiple ones do not get added!"
+                echo
+                exit 1 ;;
 
-        # PICK FROM THE RC TREE
-        "-rc"|"--release-candidate")
-            RC=true ;;
+            # Use git merge
+            "-mg"|"--merge")
+                export UPDATE_METHOD=merge ;;
 
-        # ONLY UPDATE THE REMOTES
-        "-u"|"--update-only")
-            UPDATE_ONLY=true ;;
+            # Print the latest version from kernel.org
+            "-pl"|"--print-latest")
+                export PRINT_LATEST=true ;;
 
-        # SPECIFY THE VERSION TO MERGE/CHERRY-PICK TO
-        "-v"|"--version")
-            shift && enforce_value $@
+            # Only update the linux-stable remote
+            "-u"|"--update-only")
+                export UPDATE_REMOTE_ONLY=true ;;
 
-            NEW_VERSION=${1} ;;
+            # Update to the latest version upstream unconditionally
+            "-ul"|"--update-latest")
+                export UPDATE_MODE=2 ;;
 
-        *)
-            report_error "Invalid parameter!" ;;
-    esac
+            # Update to the specified version
+            "-v"|"--version")
+                shift
+                [[ $# -lt 1 ]] && report_error "Please specify a version to update!"
 
-    shift
-done
+                export UPDATE_MODE=1
+                export VERSION_SUPPLIED=${1} ;;
+
+            *)
+                report_error "Invalid parameter!" ;;
+        esac
+
+        shift
+    done
+
+    # Sanity checks
+    [[ ! ${UPDATE_METHOD} ]] && report_error "Neither cherry-pick nor merge were specified, please supply one!" -h
+    [[ ! -f Makefile ]] && report_error "This is not being run in a kernel tree!" -h
+    [[ -z ${UPDATE_MODE} ]] && export UPDATE_MODE=0
+}
 
 
-# VERIFY REMOTE FUNCTION
+# Update the linux-stable{-rc} remotes (and add them if they doesn't exist)
 function verify_remote() {
     add_remote ${1} ${KERNEL_FOLDER}/mirrors/${1}
 
@@ -60,78 +105,85 @@ function verify_remote() {
 
     [[ $? -ne 0 ]] && report_error "Remote ${1} update failed!" \
                    || echo "Remote ${1} updated successfully!"
+
+    [[ ${UPDATE_REMOTE_ONLY} ]] && echo && exit 0
 }
 
-# GENERATE VERSIONS
-function gen_versions() {
-    [[ ${UPDATE_ONLY} ]] && exit
 
-    CUR_VERSION=$(make kernelversion)
+# Generate versions
+function generate_versions() {
+    header "Calculating versions"
 
-    MAJOR_VERSION=$(echo ${CUR_VERSION} | cut -f 1,2 -d .)
+    # Full kernel version
+    CURRENT_VERSION=$(make kernelversion)
+    # First two numbers (3.4 | 3.10 | 3.18 | 4.4)
+    CURRENT_MAJOR_VERSION=$(echo ${CURRENT_VERSION} | cut -f 1,2 -d .)
+    # Last number
+    CURRENT_SUBLEVEL=$(echo ${CURRENT_VERSION} | cut -d . -f 3)
 
-    if [[ -z ${NEW_VERSION} ]]; then
-        SUBLEVEL=$(($(echo ${CUR_VERSION} | cut -d . -f 3) + 1))
-        NEW_VERSION=${MAJOR_VERSION}.${SUBLEVEL}
-    fi
+    # Get latest update from upstream
+    LATEST_VERSION=$(git tag --sort=-taggerdate -l v${CURRENT_MAJOR_VERSION}* | head -n 1 | sed s/v//)
+    LATEST_SUBLEVEL=$(echo ${LATEST_VERSION} | cut -d . -f 3)
 
-    # SET RANGE BASED ON IF WE ARE PICKING A RELEASE OR RC BUILD
-    [[ ! ${RC} ]] && RANGE=v${CUR_VERSION}..v${NEW_VERSION} \
-                  || RANGE=v${CUR_VERSION}..stable-rc/linux-${MAJOR_VERSION}.y
+    # Print the current/latest version and exit if requested
+    echo "${BOLD}Current kernel version:${RST} ${CURRENT_VERSION}"
+    echo
+    echo "${BOLD}Latest kernel version:${RST} ${LATEST_VERSION}"
+    [[ ${PRINT_LATEST} ]] && echo && exit 0
 
-    # NUMBER OF COMMITS DIFFERENT
-    ND=$(git rev-list --count ${RANGE} 2> /dev/null)
-    [[ -z ${ND} || ${ND} -eq 0 ]] && report_error "There are no commits to pick/merge!"
+    # UPDATE_MODES:
+    # 0. Update one version
+    # 1. Update to a specified version
+    # 2. Update to the latest version
+    case ${UPDATE_MODE} in
+        0)
+            TARGET_SUBLEVEL=$((${CURRENT_SUBLEVEL} + 1))
+            TARGET_VERSION=${CURRENT_MAJOR_VERSION}.${TARGET_SUBLEVEL} ;;
+        1)
+            TARGET_VERSION=${VERSION_SUPPLIED} ;;
+        2)
+            TARGET_VERSION=${LATEST_VERSION} ;;
+    esac
 
-    export NEW_VERSION RANGE ND
+    # Make sure target version is between current version and latest version
+    TARGET_SUBLEVEL=$(echo ${TARGET_VERSION} | cut -d . -f 3)
+    [[ ${TARGET_SUBLEVEL} -le ${CURRENT_SUBLEVEL} ]] && report_error "Current version is up to date with target version ${TARGET_VERSION}!\n"
+    [[ ${TARGET_SUBLEVEL} -gt ${LATEST_SUBLEVEL} ]] && report_error "Target version ${TARGET_VERSION} does not exist!\n"
+
+    export CURRENT_VERSION TARGET_VERSION
+    export RANGE=v${CURRENT_VERSION}..v${TARGET_VERSION}
+
+    echo
+    echo "${BOLD}Target kernel version:${RST} ${TARGET_VERSION}"
+    echo
 }
 
-# MERGE FUNCTION
-function merge() {
-    [[ ${RC} ]] && TAG=stable-rc/linux-${MAJOR_VERSION}.y \
-                || TAG=v${NEW_VERSION}
 
-    header "MERGING ${NEW_VERSION}"
+function update_to_target_version() {
+    case ${UPDATE_METHOD} in
+        "cherry-pick")
+            git cherry-pick ${RANGE}
+            [[ $? -ne 0 ]] && report_error "Cherry-pick needs manual intervention! Resolve conflicts then run:
 
-    git merge ${TAG} -m "Merge ${NEW_VERSION} into $(git rev-parse --abbrev-ref HEAD)
+git add . && git cherry-pick --continue" || header "${TARGET_VERSION} PICKED CLEANLY!" ${GRN} ;;
 
-Changes in ${NEW_VERSION}: (${ND} commits)
+        "merge")
+			git merge v${TARGET_VERSION} -m "Merge ${TARGET_VERSION} into $(git rev-parse --abbrev-ref HEAD)
+
+Changes in ${TARGET_VERSION}: ($(git rev-list --count ${RANGE} 2> /dev/null) commits)
 $(git log --reverse --format="        %s" ${RANGE})
 
 Signed-off-by: $(git config --get user.name) <$(git config --get user.email)>"
 
-    [[ $? -ne 0 ]] && report_error "Merge needs manual intervention!
-    
-Resolve conflicts then run git merge --continue!" || header "${NEW_VERSION} MERGED CLEANLY!" ${GRN}
+            [[ $? -ne 0 ]] && report_error "Merge needs manual intervention!
+
+Resolve conflicts then run git merge --continue!" || header "${TARGET_VERSION} MERGED CLEANLY!" ${GRN} ;;
+    esac
 }
 
-# CHERRY-PICK FUNCTION
-function cherry_pick() {
-    header "CHERRY-PICKING ${NEW_VERSION}"
-
-    git cherry-pick ${RANGE}
-
-    [[ $? -ne 0 ]] && report_error "Cherry-pick needs manual intervention! Resolve conflicts then run:
-
-git add . && git cherry-pick --continue" || header "${NEW_VERSION} PICKED CLEANLY!" ${GRN}
-}
-
-
-# THIS MUST BE RUN IN A KERNEL TREE
-[[ ! -f Makefile ]] && report_error "Run this in a kernel tree!"
-
-# MAKE SURE STABLE REMOTES EXISTS
-header "UPDATING REMOTES"
-
+parse_parameters $@
+header "Updating remotes"
 verify_remote stable
 verify_remote stable-rc
-
-# GENERATE VERSIONS
-gen_versions
-
-# PICK OR MERGE!
-[[ ${MERGE} ]] && merge \
-               || cherry_pick
-
-# ALERT OF SCRIPT END
-echo "\a"
+generate_versions
+update_to_target_version
