crons/update_mirrors: Less boilerplate
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/crons/update_mirrors b/crons/update_mirrors
--- a/crons/update_mirrors
+++ b/crons/update_mirrors
@@ -4,11 +4,15 @@
 
 LOG=${HOME}/kernels/mirrors/cron.log
 
+function log() {
+    echo "$(date): ${1}" >> ${LOG}
+}
+
 for REPO in Clang LLVM Linux; do
-    cd ${HOME}/kernels/mirrors/${REPO,,} || { echo "$(date): ${REPO} folder doesn't exist!" >> ${LOG}; continue; }
-    git pull github master || { echo "$(date): Updating ${REPO} from GitHub failed!" >> ${LOG}; continue; }
-    git pull origin master || { echo "$(date): Updating ${REPO} from origin failed!" >> ${LOG}; continue; }
-    git push github HEAD || { echo "$(date): Pushing to GitHub failed!" >> ${LOG}; continue; }
-    echo "$(date): ${REPO} update successful" >> ${LOG}
+    cd ${HOME}/kernels/mirrors/${REPO,,} || { log "${REPO} folder doesn't exist!"; continue; }
+    git pull github master || { log "Updating ${REPO} from GitHub failed!"; continue; }
+    git pull origin master || { log "Updating ${REPO} from origin failed!"; continue; }
+    git push github HEAD || { log "Pushing to GitHub failed!"; continue; }
+    log "${REPO} update successful"
 done
 echo >> ${LOG}
