crons/update_mirrors: Format with shfmt
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/crons/update_mirrors b/crons/update_mirrors
--- a/crons/update_mirrors
+++ b/crons/update_mirrors
@@ -5,15 +5,27 @@
 LOG=${HOME}/cbl/mirrors/logs/$(date +%Y%m%d)
 
 function log() {
-    echo "$(date): ${1}" >> "${LOG}"
+    echo "$(date): ${1}" >>"${LOG}"
 }
 
 mkdir -p "$(dirname "${LOG}")"
 for REPO in LLVM Linux; do
-    cd "${HOME}/cbl/mirrors/${REPO:l}" || { log "${REPO} folder doesn't exist!"; continue; }
-    git pull github master || { log "Updating ${REPO} from GitHub failed!"; continue; }
-    git pull origin master || { log "Updating ${REPO} from origin failed!"; continue; }
-    git push github HEAD || { log "Pushing to GitHub failed!"; continue; }
+    cd "${HOME}/cbl/mirrors/${REPO:l}" || {
+        log "${REPO} folder doesn't exist!"
+        continue
+    }
+    git pull github master || {
+        log "Updating ${REPO} from GitHub failed!"
+        continue
+    }
+    git pull origin master || {
+        log "Updating ${REPO} from origin failed!"
+        continue
+    }
+    git push github HEAD || {
+        log "Pushing to GitHub failed!"
+        continue
+    }
     log "${REPO} update successful"
 done
-echo >> "${LOG}"
+echo >>"${LOG}"
