crons/update_mirrors: Reflect current branches
main for llvm-project and add for-review branch so that pull requests never get merged to master.

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/crons/update_mirrors b/crons/update_mirrors
--- a/crons/update_mirrors
+++ b/crons/update_mirrors
@@ -10,22 +10,32 @@ function log() {
 
 mkdir -p "$(dirname "${LOG}")"
 for REPO in LLVM Linux; do
+    case ${REPO} in
+        LLVM) BRANCH=main ;;
+        Linux) BRANCH=master ;;
+    esac
     cd "${HOME}/cbl/mirrors/${REPO:l}" || {
         log "${REPO} folder doesn't exist!"
         continue
     }
-    git pull github master || {
+    git pull github ${BRANCH} || {
         log "Updating ${REPO} from GitHub failed!"
         continue
     }
-    git pull origin master || {
+    git pull origin ${BRANCH} || {
         log "Updating ${REPO} from origin failed!"
         continue
     }
-    git push github HEAD || {
+    git push github HEAD:${BRANCH} || {
         log "Pushing to GitHub failed!"
         continue
     }
+    if [[ ${REPO} = "Linux" ]]; then
+        git push -f github ${BRANCH}:for-review || {
+            log "Pushing for-review branch failed!"
+            continue
+        }
+    fi
     log "${REPO} update successful"
 done
 echo >>"${LOG}"
