workstation/als: Fix shellcheck warnings
workstation/als:166:24: error: Don't quote right-hand side of =~, it'll match literally rather than as a regex. [SC2076]
workstation/als:166:41: error: Don't quote right-hand side of =~, it'll match literally rather than as a regex. [SC2076]
workstation/als:166:58: error: Don't quote right-hand side of =~, it'll match literally rather than as a regex. [SC2076]
workstation/als:198:43: note: Double quote to prevent globbing and word splitting. [SC2086]

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/workstation/als b/workstation/als
--- a/workstation/als
+++ b/workstation/als
@@ -163,7 +163,7 @@ while (( ${#} )); do
         # Versions to merge, separated by commas
         "-v"|"--versions")
             shift && enforce_value "${@}"
-            [[ ${1} =~ "4.4" || ${1} =~ "4.9" || ${1} =~ "4.14" ]] || die "Invalid version specified!"
+            [[ ${1} =~ 4.4 || ${1} =~ 4.9 || ${1} =~ 4.14 ]] || die "Invalid version specified!"
             IFS="," read -r -A VERSIONS <<< "${1}" ;;
     esac
     shift
@@ -195,7 +195,7 @@ if [[ -n ${INIT} ]]; then
                 REMOTES=( "LineageOS:https://github.com/LineageOS/android_kernel_oneplus_sdm845"
                           "upstream:https://github.com/OnePlusOSS/android_kernel_oneplus_sdm845" )
                 ( cd "${ITEM}" && git clone -b oneplus/SDM845_Q_10.0 git://github.com/OnePlusOSS/android_vendor_oneplus_opensource_kernel drivers/oneplus )
-                echo "drivers/oneplus" >> ${HOME}/.gitignore_global ;;
+                echo "drivers/oneplus" >> "${HOME}"/.gitignore_global ;;
         esac
         for REMOTE in "${REMOTES[@]}"; do
             git -C "${ITEM}" remote add "${REMOTE%%:*}" "${REMOTE#*:}"
