workstation/als: Do not push if build fails
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/workstation/als b/workstation/als
--- a/workstation/als
+++ b/workstation/als
@@ -18,14 +18,34 @@ function kv() {
 }
 
 # Steps to execute post 'git fm'
-function post_git_fm_steps() {
+function post_git_fm_steps() {(
     # Log our success
     log "${LOG_TAG} ${1}"
+    # Build if requested and not Nash
+    if [[ -n ${BUILD} ]]; then
+        # msm-4.14 has two defconfigs to build: sm8150-perf_defconfig and sdmsteppe-perf_defconfig
+        if [[ ${REPO} = "msm-4.14" && ${BRANCH} != "kernel.lnx.4.14.r1" ]]; then
+            BK_COMMANDS=( "bk" "bk -d vendor/sdmsteppe-perf_defconfig" )
+        else
+            BK_COMMANDS=( "bk" )
+        fi
+
+        for BK_COMMAND in "${BK_COMMANDS[@]}"; do
+            # Make BK_COMMAND an array
+            read -rA BK_COMMAND <<< "${BK_COMMAND}"
+            if "${BK_COMMAND[@]}"; then
+                # Show kernel version in log
+                log "${LOG_TAG} Build successful: $(kv)$(cd out || return; ../scripts/setlocalversion ..)"
+            else
+                # Add command for quick reproduction of build failure
+                log "${LOG_TAG} Build failed: ( cd ${ALS}/${REPO}; ${BK_COMMAND} )"
+                BUILD_FAILED=true
+            fi
+        done
+    fi
     # Don't push if we're just testing
-    [[ -z ${NO_PUSH} ]] && git push
-    # Make sure SKIP_BUILD gets unset
-    unset SKIP_BUILD
-}
+    [[ -z ${NO_PUSH} && -z ${BUILD_FAILED} ]] && git push
+)}
 
 # Steps to execute if merge failed
 function failed_steps() {
@@ -36,8 +56,6 @@ function failed_steps() {
     git ma
     # Reset back to origin
     git rh "origin/${BRANCH}"
-    # Skip building if requested
-    SKIP_BUILD=true
 }
 
 # Conflict commands
@@ -294,28 +312,6 @@ for VERSION in "${VERSIONS[@]}"; do
                         failed_steps
                     fi
                 fi
-            fi
-
-            # Build if requested and not Nash
-            if [[ -n ${BUILD} && -z ${SKIP_BUILD} ]]; then
-                # msm-4.14 has two defconfigs to build: sm8150-perf_defconfig and sdmsteppe-perf_defconfig
-                if [[ ${REPO} = "msm-4.14" && ${BRANCH} != "kernel.lnx.4.14.r1" ]]; then
-                    BK_COMMANDS=( "bk" "bk -d vendor/sdmsteppe-perf_defconfig" )
-                else
-                    BK_COMMANDS=( "bk" )
-                fi
-
-                for BK_COMMAND in "${BK_COMMANDS[@]}"; do
-                    # Make BK_COMMAND an array
-                    read -rA BK_COMMAND <<< "${BK_COMMAND}"
-                    if "${BK_COMMAND[@]}"; then
-                        # Show kernel version in log
-                        log "${LOG_TAG} Build successful: $(kv)$(cd out || return; ../scripts/setlocalversion ..)"
-                    else
-                        # Add command for quick reproduction of build failure
-                        log "${LOG_TAG} Build failed: ( cd ${ALS}/${REPO}; ${BK_COMMAND} )"
-                    fi
-                done
             fi
             log
         done
