os: Remove macOS support and update Linux to use hostname
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/os/common b/os/common
--- a/os/common
+++ b/os/common
@@ -2,7 +2,7 @@
 #
 # Utility and terminal setup functions (usually for .bashrc)
 #
-# Copyright (C) 2017 Nathan Chancellor
+# Copyright (C) 2017-2018 Nathan Chancellor
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -21,8 +21,8 @@
 # SOURCE OUR UNIVERSAL FUNCTIONS SCRIPT (DON'T MAC CHECK THOUGH)
 source common -m
 
-# SOURCE THE OS SPECIFIC FUNCTIONS
-source "${SCRIPTS_FOLDER}/os/${OS}"
+# SOURCE THE MACHINE SPECIFIC FUNCTIONS
+source "${SCRIPTS_FOLDER}/os/${HOST}"
 
 function aliases() {
     # tmux alias
@@ -109,12 +109,10 @@ function add_to_path_post() {
 function bash_setup() {
     aliases
     # shellcheck disable=SC2086
-    ${OS}_aliases
+    ${HOST}_aliases
     tmux_attach
     # shellcheck disable=SC2086
-    ${OS}_prompt
-    # shellcheck disable=SC2086
-    ${OS}_setup
+    ${HOST}_setup
     add_to_path_pre "${SCRIPTS_FOLDER}"
 }
 
@@ -167,4 +165,16 @@ function gerrit-push {
     else
         echo "wtf happened?"
     fi
+}
+
+
+# Function to upload to del.dog
+function deldog() {
+    RESULT=$(curl -sf --data-binary @"${1:--}" https://del.dog/documents) || {
+        echo "ERROR: failed to post document" >&2
+        exit 1
+    }
+    KEY=$(jq -r .key <<< "${RESULT}")
+    echo "https://del.dog/${KEY}"
+    echo "https://del.dog/raw/${KEY}"
 }
