os/linux: Add function to upload to del.dog
Signed-off-by: Harsh Shandilya <harsh@prjkt.io>
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/os/linux b/os/linux
--- a/os/linux
+++ b/os/linux
@@ -476,3 +476,15 @@ function sq() {
     git -C ${HOME}/kernels/sources/stable-queue pull
     git quiltimport --patches ${HOME}/kernels/sources/stable-queue/queue-${MAJOR}
 }
+
+
+# Function to upload to del.dog
+function deldog() {
+    RESULT=$(curl -sf --data-binary @${1:--} https://del.dog/documents) || {
+        echo "ERROR: failed to post document" >&2
+        exit 1
+    }
+    KEY=$(jq -r .key <<< ${RESULT})
+    echo "https://del.dog/${KEY}"
+    echo "https://del.dog/raw/${KEY}"
+}
