os/penguin: Various improvements
1. Make keys not being present only a warning (bootstrap may be run
   again after failures).
2. Fix fd/ripgrep installation failures
3. Download and source common functions if they aren't present.

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/os/penguin b/os/penguin
--- a/os/penguin
+++ b/os/penguin
@@ -9,14 +9,17 @@
 
 # Setup function
 function bootstrap() {
+    # Grab common functions/variables
+    [[ ! -f ${HOME}/scripts/common ]] && source <(curl -Ls https://github.com/nathanchance/scripts/raw/master/common)
+
     # Make sure keys are present
-    [[ ! -d ${HOME}/keys ]] && { echo -e "\033[01;31mAdd GPG and SSH keys to ${HOME}/keys!\033[0m"; return 1; }
+    [[ ! -d ${HOME}/keys ]] && { warn "${HOME}/keys not found, skipping GPG and SSH keys setup!"; NO_KEYS=true; }
 
     # Set architecture variables
     case "$(uname -m)" in
         "aarch64") ARCH=arm64 ;;
         "x86_64") ARCH=amd64 ;;
-        *) echo -e "\033[01;31mUnsupported architecture!\033[0m"; return 1 ;;
+        *) display_error "Unsupported architecture!"; return 1 ;;
     esac
 
     # Install packages from Debian repos
@@ -33,9 +36,10 @@ function bootstrap() {
     HUB_VERSION=2.5.1
     curl -LO https://github.com/github/hub/releases/download/v${HUB_VERSION}/hub-linux-${ARCH}-${HUB_VERSION}.tgz
     tar -xf hub-linux-${ARCH}-${HUB_VERSION}.tgz
-    cd hub-linux-${ARCH}-${HUB_VERSION} || return 1
+    cd hub-linux-${ARCH}-${HUB_VERSION} || { display_error "Downloading or extracting hub failed!"; return 1; }
     sudo prefix=/usr/local ./install
-    cd .. && rm -rf hub*
+    cd "${OLDPWD}" || { display_error "${OLDPWD} doesn't exist??"; return 1; }
+    rm -rf hub*
 
     # Install prebuilt ripgrep and fd binaries if available
     FD_VERSION=7.1.0
@@ -52,40 +56,39 @@ function bootstrap() {
         curl https://sh.rustup.rs -sSf | sh
         source "${HOME}"/.cargo/env
 
-        for PAIR in https://github.com/sharkdp/fd/archive/v${FD_VERSION}.zip \
-                    https://github.com/BurntSushi/ripgrep/archive/${RG_VERSION}.zip; do
+        for PAIR in fd:https://github.com/sharkdp/fd/archive/v${FD_VERSION}.zip \
+                    ripgrep:https://github.com/BurntSushi/ripgrep/archive/${RG_VERSION}.zip; do
             BINARY=${PAIR%%:*}
             URL=${PAIR#*:}
             TMP=$(mktemp)
 
             curl -L "${URL}" -o "${TMP}"
             unzip "${TMP}"
-            cd "${BINARY}"-* || return 1
+            cd "${BINARY}"-* || { display_error "Downloading or extracting ${BINARY} failed!"; return 1; }
             cargo build --release
             cargo install
-            cd "${OLDPWD}" || return 1
+            cd "${OLDPWD}" || { display_error "${OLDPWD} doesn't exist??"; return 1; }
             rm -rf "${OLDPWD}" "${TMP}"
         done
     fi
 
-    # Setup SSH
-    mkdir -p "${HOME}"/.ssh
-    mv "${HOME}"/keys/id_ed25519{,.pub} "${HOME}"/.ssh
-    chmod 600 "${HOME}"/.ssh/id_ed25519
+    # Setup SSH and GPG if keys are present
+    if [[ -z ${NO_KEYS} ]]; then
+        mkdir -p "${HOME}"/.ssh
+        mv "${HOME}"/keys/id_ed25519{,.pub} "${HOME}"/.ssh
+        chmod 600 "${HOME}"/.ssh/id_ed25519
 
-    # Setup GPG
-    gpg --import "${HOME}"/keys/{public*,private*}.asc
-    gpg --import-ownertrust "${HOME}"/keys/ownertrust*.asc
-    git config --global commit.gpgsign true
-    git config --global user.signingkey 2437CB76E544CB6AB3D9DFD399739260CB6CB716
-    {
-        echo "default-cache-ttl 3600"
-        echo "max-cache-ttl 86400"
-    } > "${HOME}"/.gnupg/gpg-agent.conf
-    gpg-connect-agent reloadagent /bye
-
-    # Remove keys
-    rm -rf "${HOME}"/keys
+        # Setup GPG
+        gpg --import "${HOME}"/keys/{public*,private*}.asc
+        gpg --import-ownertrust "${HOME}"/keys/ownertrust*.asc
+        git config --global commit.gpgsign true
+        git config --global user.signingkey 2437CB76E544CB6AB3D9DFD399739260CB6CB716
+        {
+            echo "default-cache-ttl 3600"
+            echo "max-cache-ttl 86400"
+        } > "${HOME}"/.gnupg/gpg-agent.conf
+        gpg-connect-agent reloadagent /bye
+    fi
 
     # Clone scripts
     git clone git@github.com:nathanchance/scripts "${HOME}"/scripts || return 1
