funcs/bldupdbin: Completely revamp
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/funcs/bldupdbin b/funcs/bldupdbin
--- a/funcs/bldupdbin
+++ b/funcs/bldupdbin
@@ -5,66 +5,22 @@
 # Functions to build the latest versions of certain pieces of software
 
 
-# Build/install bat
-function bibat() {(
-    [[ -z ${BAT_VERSION} ]] && BAT_VERSION=0.12.1
-    if [[ $(uname -m) = "x86_64" ]] && command -v dpkg &>/dev/null; then
-        curl -LSso ${TMP_DEB:=$(mktemp --suffix=.deb)} https://github.com/sharkdp/bat/releases/download/v${BAT_VERSION}/bat_${BAT_VERSION}_amd64.deb
-        sudo dpkg -i "${TMP_DEB}" && rm "${TMP_DEB}"
-    else
-        cd "${TMP_WKDIR:=$(mktemp -d)}"
-        curl -LSs https://github.com/sharkdp/bat/archive/v${BAT_VERSION}.tar.gz | tar -xzf -
-        cd bat-${BAT_VERSION}
-        [[ -d ${HOME}/.cargo/bin ]] || install_rust
-        path_push "${HOME}/.cargo/bin"
-        cargo build --release --locked || die "cargo build failed!"
-        cargo install --force --path . || die "cargo install failed!"
-    fi
-
-    command -v bat
-    bat --version
-)}
-
-
 # Build/update ccache
 function bccache() {(
-    [[ -z ${CCACHE_VERSION} ]] && CCACHE_VERSION=3.7.4
-    CCACHE_FOLDER=ccache-${CCACHE_VERSION}
+    [[ -z ${CCACHE_VERSION} ]] && CCACHE_VERSION=$(glr ccache/ccache)
+    CCACHE_FOLDER=ccache-${CCACHE_VERSION//v}
     TMP_FOLDER=$(mktemp -d)
     cd "${TMP_FOLDER}"
-    curl -LSs https://github.com/ccache/ccache/releases/download/v"${CCACHE_VERSION}"/"${CCACHE_FOLDER}".tar.gz | tar -xzf -
-    cd "${CCACHE_FOLDER}" || die "Downloading or extracting ccache failed!"
+    curl -LSs https://github.com/ccache/ccache/releases/download/"${CCACHE_VERSION}"/"${CCACHE_FOLDER}".tar.gz | tar -xzf -
+    cd "${CCACHE_FOLDER}" || die "Downloading or extracting ccache failed"
     ./configure --prefix="${PREFIX:=${HOME}/usr}"
-    make "${JOBS_FLAG:--j"$(nproc)"}" || die "make failed!"
-    make install || die "install failed!"
+    make "${JOBS_FLAG:--j"$(nproc)"}" || die "make failed"
+    make install || die "install failed"
     rm -rf "${TMP_FOLDER}"
 
     path_push "${PREFIX}"/bin
     command -v ccache
     ccache --version
-)}
-
-
-# Build/install fd
-function bifd() {(
-    [[ -z ${FD_VERSION} ]] && FD_VERSION=7.4.0
-    if [[ $(uname -m) = "x86_64" ]] && command -v dpkg &>/dev/null; then
-        curl -LSso ${TMP_DEB:=$(mktemp --suffix=.deb)} https://github.com/sharkdp/fd/releases/download/v${FD_VERSION}/fd_${FD_VERSION}_amd64.deb
-        sudo dpkg -i "${TMP_DEB}" && rm "${TMP_DEB}"
-    else
-        cd "${TMP_WKDIR:=$(mktemp -d)}"
-        curl -LSs https://github.com/sharkdp/fd/archive/v${FD_VERSION}.tar.gz | tar -xzf -
-        cd fd-${FD_VERSION}
-        [[ -d ${HOME}/.cargo/bin ]] || install_rust
-        path_push "${HOME}/.cargo/bin"
-        cargo build --release --locked || die "cargo build failed!"
-        cargo install --force --path . || die "cargo install failed!"
-        [[ -d ${HOME}/.zfunctions ]] || mkdir -p "${HOME}/.zfunctions"
-        install -Dm644 target/release/build/fd-find-*/out/_fd ${HOME}/.zfunctions/_fd
-    fi
-
-    command -v fd
-    fd --version
 )}
 
 
@@ -85,15 +41,15 @@ function bgit() {(
         mkdir -p "${GIT_FOLDER%/*}"
         git clone git://github.com/git/git "${GIT_FOLDER}"
     fi
-    cd "${GIT_FOLDER}" || die "Couldn't move into ${GIT_FOLDER}!"
+    cd "${GIT_FOLDER}" || die "Couldn't move into ${GIT_FOLDER}"
 
     git clean -fxdq
     git fetch
 
-    [[ -z ${GIT_VERSION} ]] && GIT_VERSION=2.23.0
-    git checkout v"${GIT_VERSION}"
+    [[ -z ${GIT_VERSION} ]] && GIT_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
+    git checkout v"${GIT_VERSION//v}"
 
-    "${MAKE[@]}" all install || die "git build/install failed!"
+    "${MAKE[@]}" all install || die "git build/install failed"
 
     if [[ -n ${ZSH_NAME} ]]; then
         mkdir -p "${PREFIX}"/share/bash-completion/completions/
@@ -128,11 +84,11 @@ function bpgollvm() {(
         esac
         shift
     done
-    [[ -z ${LLVM_VERSION} ]] && LLVM_VERSION=llvmorg-8.0.1-rc2
+    [[ -z ${LLVM_VERSION} ]] && LLVM_VERSION=master
 
     header "Updating LLVM and cleaning up"
     [[ -d ${LLVM_PROJECT} ]] || { mkdir -p "${LLVM_PROJECT%/*}"; git clone https://github.com/llvm/llvm-project "${LLVM_PROJECT}"; }
-    cd ${LLVM_PROJECT} || die "llvm-project clone failed!"
+    cd ${LLVM_PROJECT} || die "llvm-project clone failed"
     git reset --hard
     git clean -fxdq
     git fetch origin
@@ -162,8 +118,8 @@ function bpgollvm() {(
                       -DLLVM_INCLUDE_TESTS=OFF \
                       -DLLVM_TARGETS_TO_BUILD=host \
                       -DLLVM_USE_LINKER=${LINKER} \
-                      "${LLVM_PROJECT}"/llvm || die "Error configuring stage 1!"
-	ninja || die "Error building stage 1!"
+                      "${LLVM_PROJECT}"/llvm || die "Error configuring stage 1"
+	ninja || die "Error building stage 1"
     ) || exit ${?}
 
     STAGE_ONE_BIN=${BUILD_FOLDER}/stage1/bin
@@ -187,8 +143,8 @@ function bpgollvm() {(
                       -DLLVM_BUILD_INSTRUMENTED=IR \
                       -DLLVM_BUILD_RUNTIME=OFF \
                       -DLLVM_INCLUDE_GO_TESTS=OFF \
-                      "${LLVM_PROJECT}"/llvm || die "Error configuring stage 2a!"
-        ninja clang lld check-clang check-llvm || die "Error building or checking stage2a!"
+                      "${LLVM_PROJECT}"/llvm || die "Error configuring stage 2a"
+        ninja clang lld check-clang check-llvm || die "Error building or checking stage2a"
     ) || exit ${?}
 
     STAGE_TWO_BIN=${BUILD_FOLDER}/stage2a/bin
@@ -209,8 +165,8 @@ function bpgollvm() {(
         "${CMAKE[@]}" "${STAGE_TWO_BIN_DEFINES[@]}" \
                       -DCMAKE_C_FLAGS="${FLAGS}" \
                       -DCMAKE_CXX_FLAGS="${FLAGS}" \
-                      "${LLVM_PROJECT}"/llvm || die "Error configuring stage 2b!"
-        ninja || die "Error building stage 2b!"
+                      "${LLVM_PROJECT}"/llvm || die "Error configuring stage 2b"
+        ninja || die "Error building stage 2b"
     ) || exit ${?}
 
     # Stage 3: Build final compiler
@@ -222,7 +178,7 @@ function bpgollvm() {(
 
         # Merge profile data
         PROFILE_DATA=${BUILD_FOLDER}/stage3/profdata.prof
-        llvm-profdata merge -output=${PROFILE_DATA} ${BUILD_FOLDER}/stage2a/profiles/*.profraw || die "Error merging profile data!"
+        llvm-profdata merge -output=${PROFILE_DATA} ${BUILD_FOLDER}/stage2a/profiles/*.profraw || die "Error merging profile data"
 
         # Build compiler with that data
         "${CMAKE[@]}" "${STAGE_ONE_BIN_DEFINES[@]}" \
@@ -231,9 +187,9 @@ function bpgollvm() {(
                       -DCMAKE_INSTALL_PREFIX=${PREFIX:=${HOME}/usr} \
                       -DLLVM_ENABLE_LTO=Thin \
                       -DLLVM_PROFDATA_FILE=${PROFILE_DATA} \
-                      "${LLVM_PROJECT}"/llvm || die "Error configuring stage 3!"
-        ninja || die "Error building stage 3!"
-        ninja install || die "Error installing stage 3!"
+                      "${LLVM_PROJECT}"/llvm || die "Error configuring stage 3"
+        ninja || die "Error building stage 3"
+        ninja install || die "Error installing stage 3"
     ) || exit ${?}
 
     header "Final LLVM information"
@@ -255,39 +211,93 @@ function bpgollvm() {(
 
 # Build/install ripgrep
 function birg() {(
-    [[ -z ${RG_VERSION} ]] && RG_VERSION=11.0.2
+    [[ -z ${RG_VERSION} ]] && RG_VERSION=$(glr BurntSushi/ripgrep)
+    BASE_URL=https://github.com/BurntSushi/ripgrep
+    TMP_FOLDER=$(mktemp -d)
+    DEB=ripgrep_${RG_VERSION}_amd64.deb
+
+    cd "${TMP_FOLDER}"
+
     if [[ $(uname -m) = "x86_64" ]] && command -v dpkg &>/dev/null; then
-        curl -LSso ${TMP_DEB:=$(mktemp --suffix=.deb)} https://github.com/BurntSushi/ripgrep/releases/download/${RG_VERSION}/ripgrep_${RG_VERSION}_amd64.deb
-        sudo dpkg -i "${TMP_DEB}" && rm "${TMP_DEB}"
+        curl -LSsO "${BASE_URL}"/releases/download/"${RG_VERSION}"/"${DEB}" || die "Error downloading ${DEB}"
+        sudo dpkg -i "${DEB}" || die "Error installing ${DEB}"
     else
-        cd "${TMP_WKDIR:=$(mktemp -d)}"
-        curl -LSs https://github.com/BurntSushi/ripgrep/archive/${RG_VERSION}.tar.gz | tar -xzf -
-        cd ripgrep-${RG_VERSION}
+        curl -LSs "${BASE_URL}"/archive/"${RG_VERSION}".tar.gz | tar -xzf - || die "Error downloading ripgrep source"
+        cd ripgrep-"${RG_VERSION}" || die "Can't move into ripgrep source"
         [[ -d ${HOME}/.cargo/bin ]] || install_rust
         path_push "${HOME}/.cargo/bin"
-        cargo build --release --locked --features 'pcre2' || die "cargo build failed!"
-        cargo install --force --path . || die "cargo install failed!"
-        [[ -d ${HOME}/.zfunctions ]] || mkdir -p "${HOME}/.zfunctions"
-        install -Dm644 complete/_rg ${HOME}/.zfunctions/_rg
+        cargo build --release --locked --features 'pcre2' || die "cargo build failed"
+        cargo install --force --path . || die "cargo install failed"
+        if [[ -n ${ZSH_NAME} ]]; then
+            [[ -d ${HOME}/.zfunctions ]] || mkdir -p "${HOME}/.zfunctions"
+            install -Dm644 complete/_rg ${HOME}/.zfunctions/_rg
+        fi
     fi
 
     command -v rg
     rg --version
+
+    rm -rf "${TMP_FOLDER}"
+)}
+
+
+# Build/install sharkdp binaries
+function bisharkdp() {(
+    BINARIES=()
+    while (( ${#} )); do
+        case ${1} in
+            all) BINARIES=( bat diskus fd hyperfine ) ;;
+            bat|diskus|fd|hyperfine) BINARIES+=( "${1}" ) ;;
+            *) die "Unsupported binary detected" ;;
+        esac
+        shift
+    done
+
+    TMP_FOLDER=$(mktemp -d)
+    cd "${TMP_FOLDER}"
+
+    for BINARY in "${BINARIES[@]}"; do (
+        URL_BASE=https://github.com/sharkdp/"${BINARY}"
+        [[ -z ${VERSION} ]] && VERSION=$(glr sharkdp/"${BINARY}")
+        if [[ $(uname -m) = "x86_64" ]] && command -v dpkg &>/dev/null; then
+            DEB=${BINARY}_${VERSION//v}_amd64.deb
+            curl -LSsO "${URL_BASE}"/releases/download/"${VERSION}"/"${DEB}" || die "Error downloading ${DEB}"
+            sudo dpkg -i "${DEB}" || die "Error installing ${DEB}"
+        else
+            curl -LSs "${URL_BASE}"/archive/"${VERSION}".tar.gz | tar -xzf - || die "Error downloading ${BINARY} source"
+            cd "${BINARY}-${VERSION}" || die "Can't move into ${BINARY} source"
+            [[ -d ${HOME}/.cargo/bin ]] || install_rust
+            path_push "${HOME}/.cargo/bin"
+            cargo build --release --locked || die "cargo build failed"
+            cargo install --force --path . || die "cargo install failed"
+            if [[ -n ${ZSH_NAME} ]]; then
+                [[ -d ${HOME}/.zfunctions ]] || mkdir -p "${HOME}/.zfunctions"
+                case ${BINARY} in
+                    fd) install -Dm644 target/release/build/fd-find-*/out/_fd ${HOME}/.zfunctions/_fd ;;
+                esac
+            fi
+        fi
+
+        command -v "${BINARY}"
+        "${BINARY}" --version
+    ); done
+
+    rm -rf "${TMP_FOLDER}"
 )}
 
 
 # Build/update tmux
 function btmux() {(
-    [[ -z ${TMUX_VERSION} ]] && TMUX_VERSION=2.9a
+    [[ -z ${TMUX_VERSION} ]] && TMUX_VERSION=$(glr tmux/tmux)
     TMP_FOLDER=$(mktemp -d)
     TMUX_FOLDER=tmux-${TMUX_VERSION}
 
     cd "${TMP_FOLDER}"
     curl -LSs https://github.com/tmux/tmux/releases/download/"${TMUX_VERSION}"/"${TMUX_FOLDER}".tar.gz | tar -xzf -
-    cd "${TMUX_FOLDER}" || die "Downloading or extracting tmux failed!"
+    cd "${TMUX_FOLDER}" || die "Downloading or extracting tmux failed"
     ./configure --prefix="${PREFIX:=${HOME}/usr}"
-    make "${JOBS_FLAG:--j"$(nproc)"}" || die "make failed!"
-    make install || die "install failed!"
+    make "${JOBS_FLAG:--j"$(nproc)"}" || die "make failed"
+    make install || die "install failed"
     rm -rf "${TMP_FOLDER}"
 
     path_push "${PREFIX}"/bin
@@ -298,17 +308,20 @@ function btmux() {(
 
 # Build/update zsh
 function bzsh() {(
-    ZSH_VERSION=5.7.1
+    ZSH_VERSION=latest
     [[ ${#} -gt 0 ]] && ZSH_VERSION=${1}
     TMP_FOLDER=$(mktemp -d)
-    ZSH_FOLDER=zsh-${ZSH_VERSION}
 
     cd "${TMP_FOLDER}"
-    curl -LSs https://www.zsh.org/pub/"${ZSH_FOLDER}".tar.xz | tar -xJf -
-    cd "${ZSH_FOLDER}" || die "Downloading or extracting zsh failed!"
+    case ${ZSH_VERSION} in
+        latest) URL=https://sourceforge.net/projects/zsh/files/latest/download ;;
+        *) URL=https://www.zsh.org/pub/"${ZSH_FOLDER}".tar.xz ;;
+    esac
+    curl -LSs "${URL}" | tar -xJf -
+    cd zsh-* || die "Downloading or extracting zsh failed"
     ./configure --prefix="${PREFIX:=${HOME}/usr}"
-    make "${JOBS_FLAG:--j"$(nproc)"}" || die "make failed!"
-    make install || die "install failed!"
+    make "${JOBS_FLAG:--j"$(nproc)"}" || die "make failed"
+    make install || die "install failed"
     rm -rf "${TMP_FOLDER}"
 
     sudo chsh -s "${PREFIX:?}/bin/zsh" "$(whoami)"
@@ -325,11 +338,10 @@ function install_rust() {(
 
 
 function bldupdbin() {(
-    bibat || exit ${?}
     bccache || exit ${?}
-    bifd || exit ${?}
     bgit || exit ${?}
     birg || exit ${?}
+    bisharkdp all || exit ${?}
     btmux || exit ${?}
     bzsh || exit ${?}
 )}
