funcs/bldupdbin: Add QEMU
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/funcs/bldupdbin b/funcs/bldupdbin
--- a/funcs/bldupdbin
+++ b/funcs/bldupdbin
@@ -286,6 +286,56 @@ function bisharkdp() {(
 )}
 
 
+# Build/install QEMU
+function bqemu() {(
+    [[ -z ${PREFIX} ]] && PREFIX=${HOME}/usr
+    QEMU_FOLDER=${SRC_FOLDER:-${HOME}/src}/qemu
+    if [[ ! -d ${QEMU_FOLDER} ]]; then
+        mkdir -p "${QEMU_FOLDER%/*}"
+        git clone --recursive -j$(nproc) https://git.qemu.org/git/qemu.git "${QEMU_FOLDER}"
+    fi
+    cd "${QEMU_FOLDER}" || die "Couldn't move into ${QEMU_FOLDER}"
+    [[ -z ${QEMU_VERSION} ]] && QEMU_VERSION=$(git describe --abbrev=0)
+    git cl -q
+    git submodule foreach --recursive git cl -q
+    git rh
+    git submodule foreach --recursive git rh
+    git submodule deinit slirp 2>/dev/null
+    git checkout v"${QEMU_VERSION//v}"
+    ( git merge-base --is-ancestor fc1120a7f5f2d4b601003205c598077d3eb11ad2 HEAD && \
+      ! git merge-base --is-ancestor ece628fcf69cbbd4b3efb6fbd203af07609467a2 HEAD ) && \
+    git cherry-pick ece628fcf69cbbd
+
+    ./configure \
+        --disable-bluez \
+        --disable-docs \
+        --disable-gcrypt \
+        --disable-gnutls \
+        --disable-gtk \
+        --disable-libssh \
+        --disable-nettle \
+        --disable-opengl \
+        --disable-sdl \
+        --disable-strip \
+        --disable-user \
+        --disable-virglrenderer \
+        --disable-vnc-png \
+        --disable-vte \
+        --disable-xen \
+        --disable-xen-pci-passthrough \
+        --extra-cflags=-g \
+        --prefix=${PREFIX}
+
+    make -j$(nproc) install
+
+    path_push "${PREFIX}"/bin
+    for QEMU_SUFFIX in aarch64 arm mipsel ppc ppc64 x86_64; do
+        command -v qemu-system-${QEMU_SUFFIX}
+        qemu-system-${QEMU_SUFFIX} --version
+    done
+)}
+
+
 # Build/update tmux
 function btmux() {(
     [[ -z ${TMUX_VERSION} ]] && TMUX_VERSION=$(glr tmux/tmux)
@@ -342,6 +392,7 @@ function install_rust() {(
 function bldupdbin() {(
     bccache || exit ${?}
     bgit || exit ${?}
+    bqemu || exit ${?}
     birg || exit ${?}
     bisharkdp all || exit ${?}
     btmux || exit ${?}
