funcs/bldupdbin: Build ninja
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/funcs/bldupdbin b/funcs/bldupdbin
--- a/funcs/bldupdbin
+++ b/funcs/bldupdbin
@@ -142,6 +142,30 @@ function ihugo() {(
     fi
 )}
 
+
+# Build/update ninja
+function bninja() {(
+    NINJA_REPO=ninja-build/ninja
+    [[ -z ${NINJA_VERSION} ]] && NINJA_VERSION=$(glr "${NINJA_REPO}")
+    NINJA_FOLDER=ninja-${NINJA_VERSION//v}
+    TMP_FOLDER=$(mktemp -d)
+
+    cd "${TMP_FOLDER}"
+    curl -LSs https://github.com/"${NINJA_REPO}"/archive/${NINJA_VERSION}.tar.gz | tar -xzf -
+    cd "${NINJA_FOLDER}" || die "Downloading or extracting ninja failed"
+
+    ./configure.py --bootstrap
+    if [[ -f ninja ]]; then
+        cp -v ninja "${PREFIX:=${HOME}/usr}"/bin
+        rm -rf "${TMP_FOLDER}"
+
+        move_to_front_of_path "${PREFIX}"/bin
+        command -v ninja
+        ninja --version
+    fi
+)}
+
+
 # Build/install PGO'd LLVM
 function bpgollvm() {(
     CMAKE=( cmake -G Ninja
@@ -481,6 +505,7 @@ function bldupdbin() {(
     bccache || exit ${?}
     bcmake || exit ${?}
     bgit || exit ${?}
+    bninja || exit ${?}
     birg || exit ${?}
     bisharkdp all || exit ${?}
     btmux || exit ${?}
