funcs/bldupdbin: Add the ability to compiler a PGO LLVM toolchain
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/funcs/bldupdbin b/funcs/bldupdbin
--- a/funcs/bldupdbin
+++ b/funcs/bldupdbin
@@ -109,6 +109,126 @@ function bgit() {(
 )}
 
 
+# Build/install PGO'd LLVM
+function bpgollvm() {(
+    CMAKE=( cmake -G Ninja -Wno-dev -DCMAKE_BUILD_TYPE="Release" -DLLVM_ENABLE_PROJECTS=all )
+    FLAGS="-O3 -march=native -mtune=native"
+    LLVM_PROJECT=${REPO_FOLDER:-${HOME}/repos}/llvm-project
+    BUILD_FOLDER=${LLVM_PROJECT}/build
+    LLVM_VERSION=llvmorg-8.0.1-rc2
+    START=$(date +%s)
+
+    header "Updating LLVM and cleaning up"
+    [[ -d ${LLVM_PROJECT} ]] || { mkdir -p "${LLVM_PROJECT%/*}"; git clone https://github.com/llvm/llvm-project "${LLVM_PROJECT}"; }
+    cd ${LLVM_PROJECT} || die "llvm-project clone failed!"
+    git reset --hard
+    git clean -fxdq
+    git checkout "${LLVM_VERSION}"
+
+    # Stage 1: Bootstrap compiler
+    (
+        header "Building LLVM stage 1"
+		mkdir -p "${BUILD_FOLDER}"/stage1
+		cd "${BUILD_FOLDER}"/stage1 || die "Error creating stage1 build folder"
+		"${CMAKE[@]}" -DCMAKE_C_COMPILER=clang \
+                      -DCMAKE_C_FLAGS="${FLAGS}" \
+					  -DCMAKE_CXX_COMPILER=clang++ \
+                      -DCMAKE_CXX_FLAGS="${FLAGS}" \
+                      -DLLVM_CCACHE_BUILD=ON \
+					  -DLLVM_TARGETS_TO_BUILD=host \
+					  -DLLVM_USE_LINKER=lld \
+					  "${LLVM_PROJECT}"/llvm || die "Error configuring stage 1!"
+		ninja || die "Error building stage 1!"
+    ) || exit ${?}
+
+    STAGE_ONE_BIN=${BUILD_FOLDER}/stage1/bin
+    STAGE_ONE_BIN_DEFINES=( -DCMAKE_AR=${STAGE_ONE_BIN}/llvm-ar
+                            -DCMAKE_C_COMPILER=${STAGE_ONE_BIN}/clang
+                            -DCLANG_TABLEGEN=${STAGE_ONE_BIN}/clang-tblgen
+                            -DCMAKE_CXX_COMPILER=${STAGE_ONE_BIN}/clang++
+                            -DLLVM_USE_LINKER=${STAGE_ONE_BIN}/ld.lld
+                            -DLLVM_TABLEGEN=${STAGE_ONE_BIN}/llvm-tblgen
+                            -DCMAKE_RANLIB=${STAGE_ONE_BIN}/llvm-ranlib )
+
+    # Stage 2a: Instrumented compiler
+    (
+        header "Building LLVM stage 2a"
+        mkdir -p "${BUILD_FOLDER}"/stage2a
+        cd "${BUILD_FOLDER}"/stage2a || die "Error creating stage2a build folder"
+        export PATH=${STAGE_ONE_BIN:?}:${PATH}
+        "${CMAKE[@]}" "${STAGE_ONE_BIN_DEFINES[@]}" \
+                      -DCMAKE_C_FLAGS="${FLAGS}" \
+                      -DCMAKE_CXX_FLAGS="${FLAGS}" \
+                      -DLLVM_BUILD_INSTRUMENTED=IR \
+                      -DLLVM_BUILD_RUNTIME=OFF \
+                      -DLLVM_INCLUDE_GO_TESTS=OFF \
+                      "${LLVM_PROJECT}"/llvm || die "Error configuring stage 2a!"
+        ninja clang lld || die "Error building stage2a!"
+        # The Go binding tests are disabled because they fail on my machine
+        # The test suite is just for benchmark coverage, we don't want the build to
+        # fail if they do.
+        ninja check-clang check-llvm || true
+    ) || exit ${?}
+
+    STAGE_TWO_BIN=${BUILD_FOLDER}/stage2a/bin
+    STAGE_TWO_BIN_DEFINES=( -DCMAKE_AR=${STAGE_TWO_BIN}/llvm-ar
+                            -DCMAKE_C_COMPILER=${STAGE_TWO_BIN}/clang
+                            -DCLANG_TABLEGEN=${STAGE_TWO_BIN}/clang-tblgen
+                            -DCMAKE_CXX_COMPILER=${STAGE_TWO_BIN}/clang++
+                            -DLLVM_USE_LINKER=${STAGE_TWO_BIN}/ld.lld
+                            -DLLVM_TABLEGEN=${STAGE_TWO_BIN}/llvm-tblgen
+                            -DCMAKE_RANLIB=${STAGE_TWO_BIN}/llvm-ranlib )
+
+    # Stage 2b: Build clang with instrumented compiler
+    (
+        header "Building LLVM stage 2b"
+        mkdir -p "${BUILD_FOLDER}"/stage2b
+        cd "${BUILD_FOLDER}"/stage2b
+        export PATH=${STAGE_TWO_BIN:?}:${PATH}
+        "${CMAKE[@]}" "${STAGE_TWO_BIN_DEFINES[@]}" \
+                      -DCMAKE_C_FLAGS="${FLAGS}" \
+                      -DCMAKE_CXX_FLAGS="${FLAGS}" \
+                      "${LLVM_PROJECT}"/llvm || die "Error configuring stage 2b!"
+        ninja || die "Error building stage 2b!"
+    ) || exit ${?}
+
+    # Stage 3: Build final compiler
+    (
+        header "Building LLVM stage 3"
+        mkdir -p "${BUILD_FOLDER}"/stage3
+        cd "${BUILD_FOLDER}"/stage3 || die "Error creating stage 3 build folder"
+        export PATH=${STAGE_ONE_BIN:?}:${PATH}
+
+        # Merge profile data
+        PROFILE_DATA=${BUILD_FOLDER}/stage3/profdata.prof
+        llvm-profdata merge -output=${PROFILE_DATA} ${BUILD_FOLDER}/stage2a/profiles/*.profraw || die "Error merging profile data!"
+
+        # Build compiler with that data
+        "${CMAKE[@]}" "${STAGE_ONE_BIN_DEFINES[@]}" \
+                      -DCMAKE_C_FLAGS="${FLAGS} -Wno-backend-plugin" \
+                      -DCMAKE_CXX_FLAGS="${FLAGS} -Wno-backend-plugin" \
+                      -DCMAKE_INSTALL_PREFIX=${PREFIX:-${HOME}/usr} \
+                      -DLLVM_PROFDATA_FILE=${PROFILE_DATA} \
+                      "${LLVM_PROJECT}"/llvm || die "Error configuring stage 3!"
+        ninja || die "Error building stage 3!"
+        ninja install || die "Error installing stage 3!"
+    ) || exit ${?}
+
+    header "Final LLVM information"
+
+    TIME_STRING=$(format_time "${START}" "$(date +%s)")
+    echo "Total build time: ${TIME_STRING:l}"
+
+    echo
+    command -v clang
+    clang --version | head -n1
+
+    echo
+    command -v ld.lld
+    ld.lld --version
+)}
+
+
 # Build/install ripgrep
 function birg() {(
     [[ -z ${RG_VERSION} ]] && RG_VERSION=11.0.1
