funcs/cbl: tc-build has been rewriting in python
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/funcs/cbl b/funcs/cbl
--- a/funcs/cbl
+++ b/funcs/cbl
@@ -843,7 +843,7 @@ function cbl_path() {
 
 
 # Function to test build-{binutils,llvm}.sh in multiple Docker images
-function bld_llvm_bntls_sh() {(
+function bld_llvm_bntls_py() {(
     CCACHE_FOLDER=${CBL}/git/ccache
     LOG=$(mktemp); echo "Log: ${LOG}"
     SCRIPT=$(mktemp --suffix=.sh)
@@ -851,11 +851,11 @@ function bld_llvm_bntls_sh() {(
 
     mkdir -p "${CCACHE_FOLDER}"
     cd "${TC_BLD}" || die "Could not move into ${TC_BLD}!"
-    [[ -f build-llvm.sh ]] || die "build-llvm.sh script could not be found!"
+    [[ -f build-llvm.py ]] || die "build-llvm.py script could not be found!"
 
     echo '#!/usr/env/bash
 
-PACKAGES=( ccache clang cmake git python )
+PACKAGES=( ccache clang cmake git python3 )
 
 # Debian/Ubuntu
 if command -v apt-get &>/dev/null; then
@@ -885,9 +885,9 @@ ccache --set-config=cache_dir=/ccache
 
 git clone /'"${PWD##*/}"' /'"${PWD##*/}"'2 && cd /'"${PWD##*/}"'2
 
-./build-binutils.sh -t all || exit 1
-./build-llvm.sh CC=gcc || exit 1
-./build-llvm.sh CC=clang || exit 1
+./build-binutils.py -t all || exit 1
+CC=gcc ./build-llvm.py || exit 1
+CC=clang ./build-llvm.py || exit 1
 
 for FILE in clang ld.lld aarch64-linux-gnu-ld arm-linux-gnueabi-ld powerpc64le-linux-gnu-ld powerpc-linux-gnu-ld ld; do
     ./usr/bin/${FILE} --version || exit 1
