funcs/deldog: Clean up and make easier for others to use
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/funcs/deldog b/funcs/deldog
--- a/funcs/deldog
+++ b/funcs/deldog
@@ -1,10 +1,15 @@
 # Function to upload to del.dog
 function deldog() {
+    for BINARY in curl jq; do
+        command -v ${BINARY} &>/dev/null || {
+            echo "ERROR: ${BINARY} is not installed" >&2
+            exit 1
+        }
+    done
     RESULT=$(curl -sf --data-binary @"${1:--}" https://del.dog/documents) || {
-        echo "ERROR: failed to post document" >&2
+        echo "ERROR: failed to post document, ca-certificates might need to be installed" >&2
         exit 1
     }
-    KEY=$(jq -r .key <<< "${RESULT}")
-    echo "https://del.dog/raw/${KEY}"
+    echo "https://del.dog/raw/$(jq -r .key <<< "${RESULT}")"
 }
 # vi: filetype=zsh
