env/android: Rewrite to be like other env scripts
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/env/android b/env/android
--- a/env/android
+++ b/env/android
@@ -5,48 +5,94 @@
 # Utility and terminal setup functions for Termux on Android
 
 
-# Fetch this script and reload .bashrc
-function rld() {
-    curl -o ~/.bashrc https://raw.githubusercontent.com/nathanchance/scripts/master/env/android
-    source ~/.bashrc
-}
-source <(curl -Ls https://raw.githubusercontent.com/nathanchance/scripts/master/funcs/deldog)
+# Download files and set up environment
+# Requires
+# $ pkg install zsh && chsh -s zsh && echo "extra-keys = [['ESC','/','-','HOME','UP','END','PGUP'],['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN']]" > ~/.termux/termux.properties
+# GPG and SSH keys to be available in the Downloads folder
+function bootstrap() {(
+    source <(curl -LSs https://github.com/nathanchance/scripts/raw/master/common) &>/dev/null || return 1
+    source <(curl -LSs https://github.com/nathanchance/scripts/raw/master/funcs/pure) &>/dev/null || return 1
 
-
-# Update function
-function upd() {
     pkg upgrade
-}
+    termux-setup-storage
+    pkg install bison \
+                clang \
+                flex \
+                git \
+                gnupg \
+                hub \
+                jq \
+                lld \
+                llvm \
+                make \
+                mosh \
+                mutt \
+                openssl \
+                ripgrep \
+                tmux
 
-
-# Function to upload to del.dog
-function deldog() {
-    RESULT=$(curl -sf --data-binary @"${1:--}" https://del.dog/documents) || {
-        echo "ERROR: failed to post document" >&2
-        return 1
-    }
-    KEY=$(jq -r .key <<< "${RESULT}")
-    echo "https://del.dog/raw/${KEY}"
-}
-
-
-# Common WireGuard logs
-function wg_debug() {
-    COMMANDS=( "wg" "ip -s -d addr" "iptables -L -v" "ip6tables -L -v" "dmesg" )
+    # Install ssh and gpg keys
+    DOWNLOADS=${HOME}/storage/downloads
+    mkdir -p "${HOME}"/.ssh
+    cp -v "${DOWNLOADS}"/id_ed25519 "${HOME}"/.ssh
+    chmod 600 "${HOME}"/.ssh/id_ed25519
+    gpg --pinentry-mode loopback --import "${DOWNLOADS}"/{public*,private*}.asc || die "Error installing gpg keys!"
+    gpg --import-ownertrust "${DOWNLOADS}"/ownertrust*.asc || die "Error installing gpg ownertrust!"
     {
-        for COMMAND in "${COMMANDS[@]}"; do
-            su --preserve-environment -c "${COMMAND}"
-            echo
-            echo
-        done
-    } | deldog
+        echo "default-cache-ttl 604800"
+        echo "max-cache-ttl 2419200"
+    } > "${HOME}"/.gnupg/gpg-agent.conf
+    gpg-connect-agent reloadagent /bye
+
+    # Configure git
+    git config --global commit.gpgsign true
+    git config --global core.editor vim
+    git config --global sendemail.smtpEncryption tls
+    git config --global sendemail.smtpServer smtp.gmail.com
+    git config --global sendemail.smtpUser natechancellor@gmail.com
+    git config --global sendemail.smtpServerPort 587
+    git config --global user.name "Nathan Chancellor"
+    git config --global user.email "natechancellor@gmail.com"
+    git config --global user.signingkey 2437CB76E544CB6AB3D9DFD399739260CB6CB716
+
+    # Downloads scripts
+    git clone git@github.com:nathanchance/scripts
+
+    # Download and install dotfiles
+    DOTFILES=${HOME}/dotfiles
+    git clone git@github.com:nathanchance/dotfiles
+    (
+        zsh "${DOTFILES}"/common/global_gitignore.sh
+        zsh "${DOTFILES}"/common/vim/vim_setup.sh
+        zsh "${DOTFILES}"/server/zshrc.sh
+        cp -v "${DOTFILES}"/pixelbook/.tmux.conf "${HOME}"
+        gpg --pinentry-mode loopback --output "${HOME}"/.muttrc --decrypt "${DOTFILES}"/common/muttrc.gpg
+    ) || die "Error installing dotfiles"
+
+    # Install Pure prompt
+    pure_prompt
+)}
+
+
+# Android aliases
+function android_aliases() {
+    alias git='hub'
+    alias mshsvr='mosh nathan@${HETZNER_IP}'
+    alias upd='pkg upgrade'
 }
 
 
-# Setup termux environment
-function setup() {
-    pkg install curl jq openssh
-    upd
-    rld
+# Setup Android prompt
+function android_prompt() {
+    autoload -U promptinit && promptinit
+    prompt pure
 }
+
+
+# Android environment setup
+function android_setup() {
+    android_prompt
+}
+
+
 # vi: filetype=zsh
