env/cbl: Update kcbw to use Google's build infrastructure
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/env/cbl b/env/cbl
--- a/env/cbl
+++ b/env/cbl
@@ -741,69 +741,37 @@ function bldtcs() {(
 
 # kernel/common build wrapper
 function kcbw() {(
-    BUILD_FOLDER=${CBL}/android/build
-    COMMON_FOLDER=${CBL}/android/common
-    OUT_FOLDER=${BLDF}/common
+    COMMON_ROOT_FOLDER=${CBL}/android/common-repo
+    COMMON_KERNEL_SRC=${COMMON_ROOT_FOLDER}/common
 
     while (( ${#} )); do
         case ${1} in
-            arm64|x86) ARCH=${1} ;;
-            CC=*|LD=*) export "${1:?}" ;;
-            3.*|4.*) BRANCH=${1} ;;
+            3.*|4.*|5.*|mainline) BRANCH=${1} ;;
+            arm64) ARCH=aarch64 ;;
+            x86) ARCH=x86_64 ;;
         esac
         shift
     done
+    : ${ARCH:?}
 
-    BRANCH=android-${BRANCH:-4.9-q}
-    [[ -z ${LD} && ! ${BRANCH} =~ android-4.9 ]] && LD=ld.lld
-
-    cd "${BUILD_FOLDER}" || die "wtf"
-
-    case "${ARCH}:${BRANCH}" in
-        "arm64:android-4.19") CONFIG=gki_defconfig ;;
-        "arm64:"*) CONFIG=cuttlefish_defconfig ;;
-        "x86_64:"*) CONFIG=x86_64_cuttlefish_defconfig ;;
+    case ${BRANCH:=mainline} in
+        4.9|4.14) CONFIG=cuttlefish ;;
+        *) CONFIG=gki ;;
     esac
 
-    echo 'ARCH='"${ARCH:=arm64}"'
-BRANCH='"${BRANCH}"'
-'$([[ ${ARCH} = arm64 ]] && echo "CLANG_TRIPLE=aarch64-linux-gnu-")'
-'$([[ ${ARCH} = arm64 ]] && echo "CROSS_COMPILE=${CROSS_COMPILE:-"aarch64-linux-gnu-"}")'
-DEFCONFIG='"${CONFIG}"'
-EXTRA_CMDS='\'''\''
-KERNEL_DIR='"$(realpath --relative-to="${PWD}" "${COMMON_FOLDER}")"'
-POST_DEFCONFIG_CMDS="check_defconfig && update_clang_config"
-CLANG_PREBUILT_BIN='"$(realpath --relative-to="${PWD}" "${CPB:-${CBL_LLVM}}")"'
-LD_LIBRARY_PATH='"${LD_LIBRARY_PATH:-"${CBL_LLVM%/*}"/lib}"'
-LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN='"$(realpath --relative-to="${PWD}" "${GCCPB:-${CBL_BNTL}}")"'
-FILES="
-arch/'"${ARCH}"'/boot/'$(case ${ARCH} in arm64) echo "Image.gz" ;; x86) echo "bzImage" ;; esac)'
-vmlinux
-System.map
-"
-STOP_SHIP_TRACEPRINTK=1
+    # Download and setup kernel source
+    [[ -d ${COMMON_ROOT_FOLDER} ]] || mkdir -p "${COMMON_ROOT_FOLDER}"
+    cd "${COMMON_ROOT_FOLDER}" || exit ${?}
+    REPO_INIT_CMD=( repo init -u https://android.googlesource.com/kernel/manifest -b common-android-"${BRANCH}" )
+    "${REPO_INIT_CMD[@]}" &>/dev/null || die "${REPO_INIT_CMD[@]} failed (${?})"
+    [[ -d ${COMMON_KERNEL_SRC} ]] && git -C "${COMMON_KERNEL_SRC}" rh &>/dev/null
+    REPO_SYNC_CMD=( repo sync "${JOBS_FLAG}" )
+    "${REPO_SYNC_CMD[@]}" &>/dev/null || die "${REPO_SYNC_CMD[*]} failed (${?})"
 
-function update_clang_config() {
-  ${KERNEL_DIR}/scripts/config --file ${OUT_DIR}/.config \
-    -e JUMP_LABEL \
-    -e LTO_CLANG \
-    -e CFI_CLANG \
-    --set-val FRAME_WARN 2048
-  (cd ${KERNEL_DIR} && \
-    make O=${OUT_DIR} ${CC_LD_ARG} olddefconfig)
-}' > "${BUILD_CONFIG:=$(mktemp)}"
-
-    # Make path relative
-    BUILD_CONFIG=$(realpath --relative-to="${PWD}" "${BUILD_CONFIG}")
-
-    # Make sure that we are on the correct branch
-    (
-        cd "${COMMON_FOLDER}" || return
-        git ch "${BRANCH}" || { git rh -q && git ch "${BRANCH}"; }
-        git pull --rebase
-    )
-
-    OUT_DIR=${OUT_FOLDER} BUILD_CONFIG=${BUILD_CONFIG} CC="${CC:-clang}" KCFLAGS="${KCFLAGS}" LD="${LD}" ./build.sh "${@}"
+    # Build kernels with newer Clang
+    sed -i "s;CLANG_PREBUILT_BIN=.*;CLANG_PREBUILT_BIN=$(realpath --relative-to="${COMMON_ROOT_FOLDER}" "${CBL_LLVM}");g" "${COMMON_KERNEL_SRC}"/build.config.common
+    BUILD_CONFIG=common/build.config."${CONFIG}"."${ARCH}" ./build/build.sh |& rg "error:|undefined|warning:"
+    exit "${pipestatus[1]}"
 )}
 
 
@@ -841,7 +809,7 @@ function kct() {(
         )
     } > "${LOG}"
 
-    for VERSION in 4.9-q 4.14 4.19; do (
+    for VERSION in 4.9-q 4.14 4.19 5.4 mainline; do (
         START=$(date +%s)
 
         # Error log
