env/cbl: Update kct for previous kcbw update
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/env/cbl b/env/cbl
--- a/env/cbl
+++ b/env/cbl
@@ -596,7 +596,7 @@ function lt() {(
         # Basic configs are defconfigs + little endian allyesconfig
         [[ -n ${BASIC} && ! ( ${CONFIG} =~ defconfig || ${CONFIG} = "allyesconfig" ) ]] && continue
 
-        header "${ARCH}:${CONFIG}"
+        header "${ARCH}:${CONFIG}" "${BOLD}"
 
         # Start timer
         START=$(date +%s)
@@ -763,22 +763,20 @@ function kcbw() {(
     [[ -d ${COMMON_ROOT_FOLDER} ]] || mkdir -p "${COMMON_ROOT_FOLDER}"
     cd "${COMMON_ROOT_FOLDER}" || exit ${?}
     REPO_INIT_CMD=( repo init -u https://android.googlesource.com/kernel/manifest -b common-android-"${BRANCH}" )
-    "${REPO_INIT_CMD[@]}" &>/dev/null || die "${REPO_INIT_CMD[@]} failed (${?})"
-    [[ -d ${COMMON_KERNEL_SRC} ]] && git -C "${COMMON_KERNEL_SRC}" rh &>/dev/null
+    "${REPO_INIT_CMD[@]}" || die "${REPO_INIT_CMD[@]} failed (${?})"
+    [[ -d ${COMMON_KERNEL_SRC} ]] && git -C "${COMMON_KERNEL_SRC}" rh
     REPO_SYNC_CMD=( repo sync "${JOBS_FLAG}" )
-    "${REPO_SYNC_CMD[@]}" &>/dev/null || die "${REPO_SYNC_CMD[*]} failed (${?})"
+    "${REPO_SYNC_CMD[@]}" || die "${REPO_SYNC_CMD[*]} failed (${?})"
 
     # Build kernels with newer Clang
     sed -i "s;CLANG_PREBUILT_BIN=.*;CLANG_PREBUILT_BIN=$(realpath --relative-to="${COMMON_ROOT_FOLDER}" "${CBL_LLVM}");g" "${COMMON_KERNEL_SRC}"/build.config.common
-    BUILD_CONFIG=common/build.config."${CONFIG}"."${ARCH}" ./build/build.sh |& rg "error:|undefined|warning:"
-    exit "${pipestatus[1]}"
+    BUILD_CONFIG=common/build.config."${CONFIG}"."${ARCH}" ./build/build.sh
 )}
 
 
 # kernel/common build testing
 function kct() {(
-    COMMON_FOLDER=${CBL}/android/common
-    OUT_FOLDER=${BLDF}/common
+    COMMON_KERNEL_SRC=${CBL}/android/common-repo/common
 
     while (( ${#} )); do
         case ${1} in
@@ -809,43 +807,42 @@ function kct() {(
         )
     } > "${LOG}"
 
-    for VERSION in 4.9-q 4.14 4.19 5.4 mainline; do (
-        START=$(date +%s)
+    for VERSION in 4.9 4.14 4.19 5.4 mainline; do (
+        for ARCH in arm64 x86; do (
+            START=$(date +%s)
 
-        # Error log
-        ERRORS=$(mktemp)
+            # Error log
+            ERRORS=$(mktemp)
 
-        # Build kernel silently normally
-        if [[ -z ${DEBUG} ]]; then
-            kcbw arm64 "${VERSION}" |& \
-            rg --color=never "error:|warning:|undefined" |& sed "s/${COMMON_FOLDER//\//\\/}\///g" > "${ERRORS}"
-            MAKE_RESULT=${pipestatus[1]}
-        else
-            kcbw arm64 "${VERSION}"
-            MAKE_RESULT=${?}
-        fi
+            header "android-${VERSION} ${ARCH}" "${BOLD}"
 
-        # Make sure that if make fails, it gets propgated to the if statement
-        if [[ ${MAKE_RESULT} -eq 0 ]]; then
-            RESULT=successful
-        else
-            RESULT=failed
-        fi
-        TIME_STRING=$(format_time "${START}" "$(date +%s)")
-        {
-            echo "android-${VERSION} | $(cd "${COMMON_FOLDER}" || die "wtf"; git kf origin/"$(git cb)") | Build ${RESULT} in ${TIME_STRING:l}\c"
-            if [[ ${RESULT} = "successful" ]]; then
-                if O=${OUT_FOLDER} bootk arm64 &>/dev/null; then
-                    echo " | Boot successful\c"
-                else
-                    echo " | Boot failed\c"
-                fi
+            # Build kernel silently normally
+            if [[ -z ${DEBUG} ]]; then
+                kcbw "${ARCH}" "${VERSION}" |& \
+                rg --color=never "error:|warning:|undefined" |& sed "s/${COMMON_KERNEL_SRC//\//\\/}\///g" |& tee "${ERRORS}"
+                MAKE_RESULT=${pipestatus[1]}
+            else
+                kcbw "${ARCH}" "${VERSION}"
+                MAKE_RESULT=${?}
             fi
-            echo
-            [[ -z ${DEBUG} && ( -n ${SHOW_NF_WARNINGS} || ${RESULT} = "failed" ) ]] && cat "${ERRORS}"
-            echo
-        } >> "${LOG}"
-        rm "${ERRORS}"
+
+            # Make sure that if make fails, it gets propgated to the if statement
+            if [[ ${MAKE_RESULT} -eq 0 ]]; then
+                COLOR=${GRN}
+                RESULT=successful
+            else
+                COLOR=${RED}
+                RESULT=failed
+            fi
+            echo "${COLOR}Build ${RESULT}${RST}"
+            TIME_STRING=$(format_time "${START}" "$(date +%s)")
+            {
+                echo "${ARCH} android-${VERSION} | $(cd "${COMMON_KERNEL_SRC}" || die "wtf"; git kf aosp/android-${VERSION}) | Build and boot ${RESULT} in ${TIME_STRING:l}"
+                [[ -z ${DEBUG} && ( -n ${SHOW_NF_WARNINGS} || ${RESULT} = "failed" ) ]] && cat "${ERRORS}"
+                echo
+            } >> "${LOG}"
+            rm "${ERRORS}"
+        ) done
     ) done
 
     MESSAGE="kernel/common build results: $(deldog "${LOG}")"
