env: Only run git aliases on bootstrap, not startup
Speeds up zsh startup by a LARGE margin.

Before:

$ time zsh -i -c exit

real    0.827
user    0.396
sys     0.547

After:

$ time zsh -i -c exit

real    0.055
user    0.047
sys     0.015

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/env/pixelbook b/env/pixelbook
--- a/env/pixelbook
+++ b/env/pixelbook
@@ -24,7 +24,6 @@ function bootstrap() {(
     # Grab common functions/variables
     source <(curl -LSs https://github.com/nathanchance/scripts/raw/master/common) &>/dev/null
     source <(curl -LSs https://github.com/nathanchance/scripts/raw/master/constants/versions) &>/dev/null
-    source <(curl -LSs https://github.com/nathanchance/scripts/raw/master/funcs/pure) &>/dev/null
 
     # Make sure keys are present
     if [[ "$(uname -n)" = "penguin" ]]; then
@@ -147,7 +146,10 @@ function bootstrap() {(
     gpg-connect-agent reloadagent /bye
 
     # Clone scripts
-    git clone git@github.com:nathanchance/scripts "${HOME}"/scripts || die "Error cloning script!"
+    local SCRIPTS; SCRIPTS=${HOME}/scripts
+    git clone git@github.com:nathanchance/scripts "${SCRIPTS}" || die "Error cloning script!"
+    source "${SCRIPTS}"/funcs/git && git_aliases
+    source "${SCRIPTS}"/funcs/pure && pure_prompt
 
     # Clone repos
     mkdir -p "${HOME}"/repos
@@ -164,9 +166,6 @@ function bootstrap() {(
     # Run small setup scripts from dotfiles
     zsh "${DOTFILES}"/common/global_gitignore.sh
     zsh "${DOTFILES}"/common/vim/vim_setup.sh
-
-    # Install Pure prompt
-    pure_prompt
 
     # We need UTF characters in crouton for the prompt to work
     if [[ "$(uname -n)" = "localhost" ]]; then
diff --git a/env/server b/env/server
--- a/env/server
+++ b/env/server
@@ -40,10 +40,10 @@ function bootstrap() {(
     # Grab common functions
     source <(curl -LSs https://github.com/nathanchance/scripts/raw/master/common) &>/dev/null || return 1
     source <(curl -LSs https://github.com/nathanchance/scripts/raw/master/funcs/hub) &>/dev/null || return 1
-    source <(curl -LSs https://github.com/nathanchance/scripts/raw/master/funcs/pure) &>/dev/null || return 1
 
     DOTFILES=${REPO_FOLDER}/dotfiles
     KEYS=/tmp/keys
+    SCRIPTS=${MAIN_FOLDER}/scripts
 
     # Check if keys are available for installation
     [[ ! -d ${KEYS} ]] && die "${KEYS} doesn't exist, create it, and copy keys!"
@@ -151,7 +151,9 @@ function bootstrap() {(
     yay -S --needed arm-linux-gnueabi-gcc lineageos-devel || die "Error running yay!"
 
     # Download repos
-    [[ ! -d ${MAIN_FOLDER}/scripts ]] && { git -C "${MAIN_FOLDER}" clone git@github.com:nathanchance/scripts || die "Error cloning scripts!"; }
+    [[ ! -d ${SCRIPTS} ]] && { git clone git@github.com:nathanchance/scripts "${SCRIPTS}" || die "Error cloning scripts!"; }
+    source "${SCRIPTS}"/funcs/git && git_aliases
+    source "${SCRIPTS}"/funcs/pure && pure_prompt
     for REPO in chromeos-adb-fastboot dotfiles hugo-files; do
         [[ ! -d ${REPO_FOLDER}/${REPO} ]] && { git -C "${REPO_FOLDER}" clone git@github.com:nathanchance/"${REPO}" || die "Error cloning ${REPO}!"; }
     done
@@ -237,9 +239,6 @@ function bootstrap() {(
     # Install gist
     gem install gist
     "${HOME}/.gem/ruby/${RUBY_VERSION}/bin/gist" --login
-
-    # Install Pure prompt
-    pure_prompt
 
     # Reminder of things to do
     echo
