env: Make workstation setup idempotent
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/env/workstation b/env/workstation
--- a/env/workstation
+++ b/env/workstation
@@ -228,15 +228,12 @@ function bootstrap() {(
 
     # Setup keys
     KEYS=/tmp/keys
-    git clone https://github.com/nathanchance/keys "${KEYS}" || die "Error downloading keys"
+    [[ -d ${KEYS} ]] || { git clone https://github.com/nathanchance/keys "${KEYS}" || die "Error downloading keys"; }
     mv "${KEYS}"/id_ed25519{,.pub} "${HOME}"/.ssh
     chmod 600 "${HOME}"/.ssh/id_ed25519
     gpg --pinentry-mode loopback --import "${KEYS}"/{public*,private*}.asc || die "Error installing gpg keys"
     gpg --import-ownertrust "${KEYS}"/ownertrust*.asc || die "Error installing gpg ownertrust"
-    {
-        echo "default-cache-ttl 604800"
-        echo "max-cache-ttl 2419200"
-    } > "${HOME}"/.gnupg/gpg-agent.conf
+    printf 'default-cache-ttl 604800\nmax-cache-ttl 2419200\n' | tee -a "${HOME}"/.gnupg/gpg-agent.conf
     gpg-connect-agent reloadagent /bye
     rm -rf "${KEYS}"
 
@@ -253,6 +250,7 @@ function bootstrap() {(
 
     # Download repos
     [[ -d ${SCRIPTS} ]] || { git clone git@github.com:nathanchance/scripts "${SCRIPTS}" || die "Error cloning scripts"; }
+    git -C "${SCRIPTS}" pull
     source "${SCRIPTS}"/env/stubs/setup && global_gitignore && create_zshrc
     source "${SCRIPTS}"/env/stubs/bldupdbin
     [[ -n ${ARCH} ]] && bgit
@@ -279,16 +277,17 @@ function bootstrap() {(
     [[ -d ${SRC_FOLDER}/android-wireguard-module-builder ]] || git -C "${SRC_FOLDER}" clone git@github.com:WireGuard/android-wireguard-module-builder.git
 
     # Download toolchains
-    tmux new-window zsh -c "git -C ${ANDROID_TC_FOLDER} clone --single-branch https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/ clang-master"
-    git -C "${ANDROID_TC_FOLDER}" clone --depth=1 -b android-9.0.0_r1 --single-branch https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/ gcc-arm64
-    git -C "${ANDROID_TC_FOLDER}" clone --depth=1 -b android-9.0.0_r1 --single-branch https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/ gcc-arm
+    [[ -d ${ANDROID_TC_FOLDER}/clang-master ]] || tmux new-window zsh -c "git -C ${ANDROID_TC_FOLDER} clone --single-branch https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/ clang-master"
+    [[ -d ${ANDROID_TC_FOLDER}/gcc-arm ]] || ggit -C "${ANDROID_TC_FOLDER}" clone --depth=1 -b android-9.0.0_r1 --single-branch https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/ gcc-arm
+    [[ -d ${ANDROID_TC_FOLDER}/gcc-arm64 ]] || git -C "${ANDROID_TC_FOLDER}" clone --depth=1 -b android-9.0.0_r1 --single-branch https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/ gcc-arm64
     for VERSION in clang-4691093:android-9.0.0_r1 clang-r353983c:android-10.0.0_r1; do
         BRANCH=${VERSION#*:}
         VERSION=${VERSION%:*}
+        [[ -d ${ANDROID_TC_FOLDER}/${VERSION} ]] && continue
         mkdir -pv "${ANDROID_TC_FOLDER}/${VERSION}"
         curl -LSs https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/${BRANCH}/${VERSION}.tar.gz | tar -C "${ANDROID_TC_FOLDER}/${VERSION}" -xzf - || display_error "Error downloading ${VERSION}!"
     done
-    git -C "${ANDROID_TC_FOLDER}" clone https://github.com/ThankYouMario/proprietary_vendor_qcom_sdclang-6.0_linux-x86 sd-llvm-6.0.2
+    [[ -d ${ANDROID_TC_FOLDER}/sd-llvm-6.0.2 ]] || git -C "${ANDROID_TC_FOLDER}" clone https://github.com/ThankYouMario/proprietary_vendor_qcom_sdclang-6.0_linux-x86 sd-llvm-6.0.2
 
     # Grab linux, linux-next, and linux-stable for CBL
     for REPO in linux linux-next linux-stable; do
@@ -299,10 +298,10 @@ function bootstrap() {(
     tmux new-window zsh -c "source ${SCRIPTS}/env/stubs/setup && cbl_other_repos"
 
     # Clone sonyxperiadev/kernel
-    git -C "${KERNEL_FOLDER}/sony" clone git://github.com/sonyxperiadev/kernel
+    [[ git -C "${KERNEL_FOLDER}/sony" clone git://github.com/sonyxperiadev/kernel
 
     # Use new GPG keyserver
-    echo "keyserver hkps://keys.openpgp.org" >> "${HOME}"/.gnupg/dirmngr.conf
+    grep -q keyserver "${HOME}/.gnupg/dirmngr.conf" || echo "keyserver hkps://keys.openpgp.org" | tee -a "${HOME}"/.gnupg/dirmngr.conf
 
     # Reminder of things to do
     set +x
