env: Update key installation
Signed-off-by: Nathan Chancellor <nathan@kernel.org>

diff --git a/env/workstation b/env/workstation
--- a/env/workstation
+++ b/env/workstation
@@ -257,8 +257,9 @@ function bootstrap() { (
             ssh-add "${HOME}"/.ssh/id_ed25519
         fi
         if ${INSTALL_GPG_KEY}; then
-            gpg --pinentry-mode loopback --import "${KEYS}"/{public*,private*}.asc || die "Error installing gpg keys"
-            gpg --import-ownertrust "${KEYS}"/ownertrust*.asc || die "Error installing gpg ownertrust"
+            gpg --pinentry-mode loopback --import "${KEYS}"/signing/private.asc || die "Error installing gpg keys"
+            gpg --import "${KEYS}"/main/public.asc || die "Error installing gpg keys"
+            gpg --import-ownertrust "${KEYS}"/main/ownertrust*.asc || die "Error installing gpg ownertrust"
             printf 'default-cache-ttl 604800\nmax-cache-ttl 2419200\n' | tee -a "${HOME}"/.gnupg/gpg-agent.conf
             gpg-connect-agent reloadagent /bye
         fi
diff --git a/env/wsl b/env/wsl
--- a/env/wsl
+++ b/env/wsl
@@ -146,8 +146,9 @@ function bootstrap() { (
 
     # Setup GPG
     if ! gpg_key_usable; then
-        gpg --pinentry-mode loopback --import "${KEYS}"/{public*,private}.asc
-        gpg --import-ownertrust "${KEYS}"/ownertrust*.asc
+        gpg --pinentry-mode loopback --import "${KEYS}"/signing/private.asc || die "Error installing gpg keys"
+        gpg --import "${KEYS}"/main/public.asc || die "Error installing gpg keys"
+        gpg --import-ownertrust "${KEYS}"/main/ownertrust*.asc || die "Error installing gpg ownertrust"
         printf 'default-cache-ttl 604800\nmax-cache-ttl 2419200\n' | tee "${HOME}"/.gnupg/gpg-agent.conf
         gpg-connect-agent reloadagent /bye
     fi
