env/workstation: First step to supporting multiple operating systems
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/env/workstation b/env/workstation
--- a/env/workstation
+++ b/env/workstation
@@ -51,77 +51,89 @@ function bootstrap() {(
              "${CBL}"/{android,git,mirrors} \
              "${GITHUB_FOLDER}" \
              "${HOME}"/usr/bin \
-             "${KERNEL_FOLDER}"/sony || die "Can't create folders, wtf?"
+             "${KERNEL_FOLDER}"/sony \
+             "${SRC_FOLDER}" || die "Can't create folders, wtf?"
 
-    # Enable multilib
-    sudo sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf
-
-    # Custom makepkg config
-    sudo sed -i "s/#MAKEFLAGS=\"-j2\"/MAKEFLAGS=\"-j$(nproc --all)\"/g" /etc/makepkg.conf
-    sudo sed -i 's/!ccache/ccache/g' /etc/makepkg.conf
+    case "$(cat /usr/lib/os-release)" in
+        *"Arch Linux"*) ARCH=true ;;
+        *"Ubuntu"*) UBUNTU=true ;;
+        *) die "Distro not supported by this function!" ;;
+    esac
 
     # Set the correct time
     sudo timedatectl set-timezone America/Phoenix
 
-    # Install required binaries
-    sudo pacman -Syyu --noconfirm || die "Error updating packages!"
-    sudo pacman -S --needed --noconfirm aarch64-linux-gnu-gcc \
-                                        asciidoc \
-                                        base-devel \
-                                        bat \
-                                        bc \
-                                        ca-certificates \
-                                        clang \
-                                        ccache \
-                                        cmake \
-                                        cpio \
-                                        doxygen \
-                                        dtc \
-                                        expect \
-                                        fd \
-                                        git \
-                                        htop \
-                                        hugo \
-                                        iputils \
-                                        jq \
-                                        linux-zen \
-                                        linux-zen-headers \
-                                        lld \
-                                        llvm \
-                                        mosh \
-                                        most \
-                                        multilib-devel \
-                                        mutt \
-                                        neofetch \
-                                        ninja \
-                                        openssl \
-                                        pacman-contrib \
-                                        perl-authen-sasl \
-                                        perl-mime-tools \
-                                        perl-net-smtp-ssl \
-                                        podman \
-                                        python \
-                                        python-pip \
-                                        python-psutil \
-                                        qemu-headless-arch-extra \
-                                        ripgrep \
-                                        rubygems \
-                                        swig \
-                                        tmux \
-                                        uboot-tools \
-                                        unzip \
-                                        wget \
-                                        xmlto || die "Error installing packages!"
-    sudo pacman -R --noconfirm linux
-    sudo grub-mkconfig -o /boot/grub/grub.cfg
+    if [[ -n ${ARCH} ]]; then
+        # Enable multilib
+        sudo sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf
+
+        # Custom makepkg config
+        sudo sed -i "s/#MAKEFLAGS=\"-j2\"/MAKEFLAGS=\"-j$(nproc --all)\"/g" /etc/makepkg.conf
+        sudo sed -i 's/!ccache/ccache/g' /etc/makepkg.conf
+
+        # Install required binaries
+        sudo pacman -Syyu --noconfirm || die "Error updating packages!"
+        sudo pacman -S --needed --noconfirm aarch64-linux-gnu-gcc \
+                                            asciidoc \
+                                            base-devel \
+                                            bat \
+                                            bc \
+                                            ca-certificates \
+                                            clang \
+                                            ccache \
+                                            cmake \
+                                            cpio \
+                                            doxygen \
+                                            dtc \
+                                            expect \
+                                            fd \
+                                            git \
+                                            htop \
+                                            hugo \
+                                            iputils \
+                                            jq \
+                                            linux-zen \
+                                            linux-zen-headers \
+                                            lld \
+                                            llvm \
+                                            mosh \
+                                            most \
+                                            multilib-devel \
+                                            mutt \
+                                            neofetch \
+                                            ninja \
+                                            openssl \
+                                            pacman-contrib \
+                                            perl-authen-sasl \
+                                            perl-mime-tools \
+                                            perl-net-smtp-ssl \
+                                            podman \
+                                            python \
+                                            python-pip \
+                                            python-psutil \
+                                            qemu-headless-arch-extra \
+                                            ripgrep \
+                                            rubygems \
+                                            swig \
+                                            tmux \
+                                            uboot-tools \
+                                            unzip \
+                                            wget \
+                                            xmlto || die "Error installing packages!"
+        sudo pacman -R --noconfirm linux
+        sudo grub-mkconfig -o /boot/grub/grub.cfg
+
+        # Configure podman
+        echo "kernel.unprivileged_userns_clone=1" | sudo tee /etc/sysctl.d/unprivileged_userns_clone.conf
+        echo "$(whoami):100000:65536" | sudo tee /etc/subgid /etc/subuid
+        echo "session    optional   pam_cgfs.so          -c freezer,memory,name=systemd,unified" | sudo tee -a /etc/pam.d/system-login
+
+        # Build folder size
+        BFS=20
+    fi
 
     # Setup build folder
-    echo "tmpfs ${BLDF} tmpfs nodev,nosuid,uid=$(whoami),gid=$(whoami),size=30G 0 0" | sudo tee -a /etc/fstab
-
-    # Configure podman
-    echo "kernel.unprivileged_userns_clone=1" | sudo tee /etc/sysctl.d/unprivileged_userns_clone.conf
-    echo "$(whoami):100000:65536" | sudo tee /etc/subgid /etc/subuid
-    echo "session    optional   pam_cgfs.so          -c freezer,memory,name=systemd,unified" | sudo tee -a /etc/pam.d/system-login
+    echo "tmpfs ${BLDF} tmpfs nodev,nosuid,uid=$(whoami),gid=$(whoami),size=${BFS}G 0 0" | sudo tee -a /etc/fstab
 
     # Download and install mkdtimg
     MKDTIMG_FOLDER=$(mktemp -d)
@@ -142,23 +154,27 @@ function bootstrap() {(
     rm -rf "${KEYS}"
 
     # Install yay and AUR packages
-    cd "${TMP_BLD_FOLDER:=$(mktemp -d)}" || die "wtf?"
-    curl -LSso PKGBUILD "https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=yay"
-    makepkg --noconfirm -si || die "Error installing yay!"
-    curl -LSso "${TMP_GPG:=$(mktemp)}" https://invisible-island.net/public/dickey-invisible-island.txt || die "Could not download GPG key!"
-    gpg --import "${TMP_GPG}" || die "Could not import GPG key!"
-    yay -S --noconfirm --needed ncurses5-compat-libs || die "Error building AUR packages!"
-    yay -S --noconfirm --needed creduce-git
+    if [[ -n ${ARCH} ]]; then
+        cd "${TMP_BLD_FOLDER:=$(mktemp -d)}" || die "wtf?"
+        curl -LSso PKGBUILD "https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=yay"
+        makepkg --noconfirm -si || die "Error installing yay!"
+        curl -LSso "${TMP_GPG:=$(mktemp)}" https://invisible-island.net/public/dickey-invisible-island.txt || die "Could not download GPG key!"
+        gpg --import "${TMP_GPG}" || die "Could not import GPG key!"
+        yay -S --noconfirm --needed ncurses5-compat-libs || die "Error building AUR packages!"
+        yay -S --noconfirm --needed creduce-git
+    fi
 
     # Download repos
     [[ ! -d ${SCRIPTS} ]] && { git clone git@github.com:nathanchance/scripts "${SCRIPTS}" || die "Error cloning scripts!"; }
     source "${SCRIPTS}"/env/setup && global_gitignore && create_zshrc
-    source "${SCRIPTS}"/funcs/bldupdbin && bgit
+    source "${SCRIPTS}"/funcs/bldupdbin
+    [[ -n ${ARCH} ]] && bgit
+    [[ -n ${UBUNTU} ]] && bldupdbin
     path_push "${HOME}/usr/bin"
     source "${SCRIPTS}"/funcs/git && git_setup
     source "${SCRIPTS}"/funcs/pure && pure_prompt
     zsh "${SCRIPTS}"/configs/common/vim/vim_setup.sh
-    ln -fs "${SCRIPTS}"/configs.workstation/.tmux.conf "${HOME}"/.tmux.conf
+    ln -fs "${SCRIPTS}"/configs/workstation/.tmux.conf "${HOME}"/.tmux.conf
     gpg --pinentry-mode loopback --output "${MAIN_FOLDER}"/.botinfo --decrypt "${SCRIPTS}"/configs/common/botinfo.gpg
     gpg --pinentry-mode loopback --output "${HOME}"/.muttrc --decrypt "${SCRIPTS}"/configs/common/muttrc.gpg
     for REPO in chromeos-adb-fastboot hugo-files nathanchance.github.io patches; do
@@ -170,7 +186,7 @@ function bootstrap() {(
     git -C "${ANDROID_TC_FOLDER}" clone --single-branch https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/ clang-master
     git -C "${ANDROID_TC_FOLDER}" clone --depth=1 -b android-9.0.0_r1 --single-branch https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/ gcc-arm64
     git -C "${ANDROID_TC_FOLDER}" clone --depth=1 -b android-9.0.0_r1 --single-branch https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/ gcc-arm
-    for VERSION in clang-4691093:android-9.0.0_r1 clang-r349610b:a59d17df840d203e477534a3312b36e2310712d0; do
+    for VERSION in clang-4691093:android-9.0.0_r1 clang-r353983c:android-10.0.0_r1; do
         BRANCH=${VERSION#*:}
         VERSION=${VERSION%:*}
         mkdir -pv "${ANDROID_TC_FOLDER}/${VERSION}"
@@ -181,8 +197,13 @@ function bootstrap() {(
     # Grab linux, linux-next, and linux-stable for CBL
     # https://www.kernel.org/cloning-linux-from-a-bundle.html
     (
-        cd "${CBL}" || die "wtf?"
-        for COMBO in torvalds/linux.git:linux torvalds/linux.git:mirrors/linux next/linux-next.git:linux-next stable/linux.git:linux-stable; do
+        cd "${SRC_FOLDER}" || die "wtf?"
+        for COMBO in torvalds/linux.git:linux \
+                     torvalds/linux.git:${CBL}/linux \
+                     torvalds/linux.git:${CBL}/mirrors/linux \
+                     next/linux-next.git:linux-next \
+                     next/linux-next.git:${CBL}/linux-next \
+                     stable/linux.git:linux-stable; do
             FOLDER=${COMBO#*:}
             URL=${COMBO%:*}
             CB=clone.bundle-${FOLDER##*/}
@@ -199,7 +220,7 @@ function bootstrap() {(
             )
         done
         rm -rf clone.bundle-*
-        git clone -b personal git@github.com:nathanchance/tc-build.git
+        git -C "${CBL}" clone -b personal git@github.com:nathanchance/tc-build.git
     )
 
     # Download other CBL things
@@ -209,6 +230,7 @@ function bootstrap() {(
         git clone https://android.googlesource.com/kernel/common
         curl -LSso common/.git/hooks/commit-msg https://android-review.googlesource.com/tools/hooks/commit-msg
         chmod u+x common/.git/hooks/commit-msg
+        git clone git@github.com:nathanchance/android-kernel-clang.git
 
         cd "${CBL}"/git || die "wtf?"
         git clone git@github.com:ClangBuiltLinux/continuous-integration.git ci
@@ -230,7 +252,7 @@ function bootstrap() {(
     git -C "${KERNEL_FOLDER}/sony" clone git://github.com/sonyxperiadev/kernel
 
     # Clone marlin and msm-3.18 repos (for pulling their upstream updates, not stables)
-    (
+    if [[ -n ${ARCH} ]]; then (
         cd "${ALS}"
         for REPO in msm-3.18:https://source.codeaurora.org/quic/la/kernel/msm-3.18 marlin:https://android.googlesource.com/kernel/msm/; do
             URL=${REPO#*:}
@@ -242,11 +264,11 @@ function bootstrap() {(
                 git fetch upstream || { display_error "Couldn't fetch ${URL}"; continue; }
             )
         done
-    )
+    ); fi
 
     # Install gist
-    gem install gist
-    "${HOME}/.gem/ruby/2.6.0/bin/gist" --login
+    gem install --user-install gist
+    "$(gem env | grep "USER INSTALL" | sed 's/.*: //')/bin/gist" --login
 
     # Use new GPG keyserver
     echo "keyserver hkps://keys.openpgp.org" >> "${HOME}"/.gnupg/dirmngr.conf
@@ -317,7 +339,7 @@ function workstation_setup() {
     source "${SCRIPTS_FOLDER}"/env/cbl
     source "${SCRIPTS_FOLDER}"/funcs/bk
     source "${SCRIPTS_FOLDER}"/funcs/bldgcc
-    add_to_path_post "${HOME}/.gem/ruby/2.6.0/bin"
+    add_to_path_post "$(gem env | grep "USER INSTALL" | sed 's/.*: //')/bin"
     load_botinfo
     type crbf &>/dev/null && crbf
     ( gpg_available )
