env: Do not try to install GPG key again if it already exists
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/env/workstation b/env/workstation
--- a/env/workstation
+++ b/env/workstation
@@ -231,10 +231,12 @@ function bootstrap() {(
     [[ -d ${KEYS} ]] || { git clone https://github.com/nathanchance/keys "${KEYS}" || die "Error downloading keys"; }
     mv "${KEYS}"/id_ed25519{,.pub} "${HOME}"/.ssh
     chmod 600 "${HOME}"/.ssh/id_ed25519
-    gpg --pinentry-mode loopback --import "${KEYS}"/{public*,private*}.asc || die "Error installing gpg keys"
-    gpg --import-ownertrust "${KEYS}"/ownertrust*.asc || die "Error installing gpg ownertrust"
-    printf 'default-cache-ttl 604800\nmax-cache-ttl 2419200\n' | tee -a "${HOME}"/.gnupg/gpg-agent.conf
-    gpg-connect-agent reloadagent /bye
+    if ! gpg_key_usable; then
+        gpg --pinentry-mode loopback --import "${KEYS}"/{public*,private*}.asc || die "Error installing gpg keys"
+        gpg --import-ownertrust "${KEYS}"/ownertrust*.asc || die "Error installing gpg ownertrust"
+        printf 'default-cache-ttl 604800\nmax-cache-ttl 2419200\n' | tee -a "${HOME}"/.gnupg/gpg-agent.conf
+        gpg-connect-agent reloadagent /bye
+    fi
     rm -rf "${KEYS}"
 
     # Install yay and AUR packages
