env: Install arcanist
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/env/workstation b/env/workstation
--- a/env/workstation
+++ b/env/workstation
@@ -352,6 +352,7 @@ function rbld_usr() { (
             bdtc || die "Error building dtc"
             bqemu || die "Error building QEMU"
             iandroidtools || die "Error installing Android tools"
+            iarc || die "Error installing arcanist"
             ib4 || die "Error installing b4"
             if [[ -d ${LLVM_TC_FOLDER} ]]; then
                 # This will never not be alphanumeric and find is insanely convoluted
