env/workstation: Update error handling
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/env/workstation b/env/workstation
--- a/env/workstation
+++ b/env/workstation
@@ -55,7 +55,7 @@ function bootstrap() {(
              "${GITHUB_FOLDER}" \
              "${HOME}"/usr/bin \
              "${KERNEL_FOLDER}"/sony \
-             "${SRC_FOLDER}" || die "Can't create folders, wtf?"
+             "${SRC_FOLDER}" || die "Can't create folders, wtf"
 
     # Set distro
     set_distro || exit ${?}
@@ -224,11 +224,11 @@ function bootstrap() {(
 
     # Setup keys
     KEYS=/tmp/keys
-    git clone https://github.com/nathanchance/keys "${KEYS}"
+    git clone https://github.com/nathanchance/keys "${KEYS}" || die "Error downloading keys"
     mv "${KEYS}"/id_ed25519{,.pub} "${HOME}"/.ssh
     chmod 600 "${HOME}"/.ssh/id_ed25519
-    gpg --pinentry-mode loopback --import "${KEYS}"/{public*,private*}.asc || die "Error installing gpg keys!"
-    gpg --import-ownertrust "${KEYS}"/ownertrust*.asc || die "Error installing gpg ownertrust!"
+    gpg --pinentry-mode loopback --import "${KEYS}"/{public*,private*}.asc || die "Error installing gpg keys"
+    gpg --import-ownertrust "${KEYS}"/ownertrust*.asc || die "Error installing gpg ownertrust"
     {
         echo "default-cache-ttl 604800"
         echo "max-cache-ttl 2419200"
@@ -238,21 +238,28 @@ function bootstrap() {(
 
     # Install yay and AUR packages
     if [[ -n ${ARCH} ]]; then
-        cd "${TMP_BLD_FOLDER:=$(mktemp -d)}" || die "wtf?"
+        cd "${TMP_BLD_FOLDER:=$(mktemp -d)}" || die "wtf"
         curl -LSso PKGBUILD "https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=yay"
-        makepkg --noconfirm -si || die "Error installing yay!"
-        curl -LSso "${TMP_GPG:=$(mktemp)}" https://invisible-island.net/public/dickey-invisible-island.txt || die "Could not download GPG key!"
-        gpg --import "${TMP_GPG}" || die "Could not import GPG key!"
-        yay -S --noconfirm --needed ncurses5-compat-libs || die "Error building AUR packages!"
+        makepkg --noconfirm -si || die "Error installing yay"
+        curl -LSso "${TMP_GPG:=$(mktemp)}" https://invisible-island.net/public/dickey-invisible-island.txt || die "Could not download GPG key"
+        gpg --import "${TMP_GPG}" || die "Could not import GPG key"
+        yay -S --noconfirm --needed ncurses5-compat-libs || die "Error building AUR packages"
         yay -S --noconfirm --needed creduce-git
     fi
 
     # Download repos
-    [[ -d ${SCRIPTS} ]] || { git clone git@github.com:nathanchance/scripts "${SCRIPTS}" || die "Error cloning scripts!"; }
+    [[ -d ${SCRIPTS} ]] || { git clone git@github.com:nathanchance/scripts "${SCRIPTS}" || die "Error cloning scripts"; }
     source "${SCRIPTS}"/env/setup && global_gitignore && create_zshrc
     source "${SCRIPTS}"/funcs/bldupdbin
     [[ -n ${ARCH} ]] && bgit
-    [[ -n ${UBUNTU} ]] && { bldupdbin && bcttlfshtools && bdtc && bqemu && install_android_tools && iub4; }
+    [[ -n ${UBUNTU} ]] && {
+        bldupdbin || die "Error installing updated binaries"
+        bcttlfshtools || die "Error installing Cuttlefish host package"
+        bdtc || die "Error building dtc"
+        bqemu || die "Error building QEMU"
+        install_android_tools || die "Error installing Android tools"
+        iub4 || die "Error installing b4"
+    }
     path_push "${HOME}/usr/bin"
     source "${SCRIPTS}"/funcs/git && git_setup
     source "${SCRIPTS}"/funcs/pure && pure_prompt
@@ -305,9 +312,7 @@ function bootstrap() {(
         echo "2. sudo reboot"
     elif [[ -n ${UBUNTU} ]]; then
         echo
-        echo "2. sudo dpkg -l | rg '4.15' && sudo apt remove"
-        echo
-        echo "3. sudo systemctl reboot"
+        echo "2. sudo systemctl reboot"
     fi
     echo
 ) || return 1; }
