env/wsl: Install b4
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/env/wsl b/env/wsl
--- a/env/wsl
+++ b/env/wsl
@@ -174,6 +174,7 @@ function rbld_usr() { (
     source "${SCRIPTS_FOLDER:?}"/env/stubs/updbin || die "Cannot source updbin"
     rm -rf "${HOME:?}"/usr
     updbin || die "updbin failed"
+    ib4 || die "ib4 failed"
     ihugo || die "ihugo failed"
     ipneofetch || die "ipneofetch failed"
     if [[ -d ${LLVM_TC_FOLDER} ]]; then
